// Code generated by protoc-gen-go.
// source: data_logs.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

type BuddyPokemonLogEntry_Result int32

const (
	BuddyPokemonLogEntry_UNSET       BuddyPokemonLogEntry_Result = 0
	BuddyPokemonLogEntry_CANDY_FOUND BuddyPokemonLogEntry_Result = 1
)

var BuddyPokemonLogEntry_Result_name = map[int32]string{
	0: "UNSET",
	1: "CANDY_FOUND",
}
var BuddyPokemonLogEntry_Result_value = map[string]int32{
	"UNSET":       0,
	"CANDY_FOUND": 1,
}

func (x BuddyPokemonLogEntry_Result) String() string {
	return proto.EnumName(BuddyPokemonLogEntry_Result_name, int32(x))
}
func (BuddyPokemonLogEntry_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor21, []int{1, 0}
}

type FortSearchLogEntry_Result int32

const (
	FortSearchLogEntry_UNSET   FortSearchLogEntry_Result = 0
	FortSearchLogEntry_SUCCESS FortSearchLogEntry_Result = 1
)

var FortSearchLogEntry_Result_name = map[int32]string{
	0: "UNSET",
	1: "SUCCESS",
}
var FortSearchLogEntry_Result_value = map[string]int32{
	"UNSET":   0,
	"SUCCESS": 1,
}

func (x FortSearchLogEntry_Result) String() string {
	return proto.EnumName(FortSearchLogEntry_Result_name, int32(x))
}
func (FortSearchLogEntry_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor21, []int{2, 0}
}

type CatchPokemonLogEntry_Result int32

const (
	CatchPokemonLogEntry_UNSET            CatchPokemonLogEntry_Result = 0
	CatchPokemonLogEntry_POKEMON_CAPTURED CatchPokemonLogEntry_Result = 1
	CatchPokemonLogEntry_POKEMON_FLED     CatchPokemonLogEntry_Result = 2
	CatchPokemonLogEntry_POKEMON_HATCHED  CatchPokemonLogEntry_Result = 3
)

var CatchPokemonLogEntry_Result_name = map[int32]string{
	0: "UNSET",
	1: "POKEMON_CAPTURED",
	2: "POKEMON_FLED",
	3: "POKEMON_HATCHED",
}
var CatchPokemonLogEntry_Result_value = map[string]int32{
	"UNSET":            0,
	"POKEMON_CAPTURED": 1,
	"POKEMON_FLED":     2,
	"POKEMON_HATCHED":  3,
}

func (x CatchPokemonLogEntry_Result) String() string {
	return proto.EnumName(CatchPokemonLogEntry_Result_name, int32(x))
}
func (CatchPokemonLogEntry_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor21, []int{3, 0}
}

type ActionLogEntry struct {
	TimestampMs int64 `protobuf:"varint,1,opt,name=timestamp_ms" json:"timestamp_ms,omitempty"`
	Sfida       bool  `protobuf:"varint,2,opt,name=sfida" json:"sfida,omitempty"`
	// Types that are valid to be assigned to Action:
	//	*ActionLogEntry_CatchPokemon
	//	*ActionLogEntry_FortSearch
	//	*ActionLogEntry_BuddyPokemon
	Action isActionLogEntry_Action `protobuf_oneof:"Action"`
}

func (m *ActionLogEntry) Reset()                    { *m = ActionLogEntry{} }
func (m *ActionLogEntry) String() string            { return proto.CompactTextString(m) }
func (*ActionLogEntry) ProtoMessage()               {}
func (*ActionLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{0} }

type isActionLogEntry_Action interface {
	isActionLogEntry_Action()
}

type ActionLogEntry_CatchPokemon struct {
	CatchPokemon *CatchPokemonLogEntry `protobuf:"bytes,3,opt,name=catch_pokemon,oneof"`
}
type ActionLogEntry_FortSearch struct {
	FortSearch *FortSearchLogEntry `protobuf:"bytes,4,opt,name=fort_search,oneof"`
}
type ActionLogEntry_BuddyPokemon struct {
	BuddyPokemon *BuddyPokemonLogEntry `protobuf:"bytes,5,opt,name=buddy_pokemon,oneof"`
}

func (*ActionLogEntry_CatchPokemon) isActionLogEntry_Action() {}
func (*ActionLogEntry_FortSearch) isActionLogEntry_Action()   {}
func (*ActionLogEntry_BuddyPokemon) isActionLogEntry_Action() {}

func (m *ActionLogEntry) GetAction() isActionLogEntry_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ActionLogEntry) GetCatchPokemon() *CatchPokemonLogEntry {
	if x, ok := m.GetAction().(*ActionLogEntry_CatchPokemon); ok {
		return x.CatchPokemon
	}
	return nil
}

func (m *ActionLogEntry) GetFortSearch() *FortSearchLogEntry {
	if x, ok := m.GetAction().(*ActionLogEntry_FortSearch); ok {
		return x.FortSearch
	}
	return nil
}

func (m *ActionLogEntry) GetBuddyPokemon() *BuddyPokemonLogEntry {
	if x, ok := m.GetAction().(*ActionLogEntry_BuddyPokemon); ok {
		return x.BuddyPokemon
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ActionLogEntry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ActionLogEntry_OneofMarshaler, _ActionLogEntry_OneofUnmarshaler, _ActionLogEntry_OneofSizer, []interface{}{
		(*ActionLogEntry_CatchPokemon)(nil),
		(*ActionLogEntry_FortSearch)(nil),
		(*ActionLogEntry_BuddyPokemon)(nil),
	}
}

func _ActionLogEntry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ActionLogEntry)
	// Action
	switch x := m.Action.(type) {
	case *ActionLogEntry_CatchPokemon:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CatchPokemon); err != nil {
			return err
		}
	case *ActionLogEntry_FortSearch:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FortSearch); err != nil {
			return err
		}
	case *ActionLogEntry_BuddyPokemon:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BuddyPokemon); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ActionLogEntry.Action has unexpected type %T", x)
	}
	return nil
}

func _ActionLogEntry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ActionLogEntry)
	switch tag {
	case 3: // Action.catch_pokemon
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CatchPokemonLogEntry)
		err := b.DecodeMessage(msg)
		m.Action = &ActionLogEntry_CatchPokemon{msg}
		return true, err
	case 4: // Action.fort_search
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FortSearchLogEntry)
		err := b.DecodeMessage(msg)
		m.Action = &ActionLogEntry_FortSearch{msg}
		return true, err
	case 5: // Action.buddy_pokemon
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BuddyPokemonLogEntry)
		err := b.DecodeMessage(msg)
		m.Action = &ActionLogEntry_BuddyPokemon{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ActionLogEntry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ActionLogEntry)
	// Action
	switch x := m.Action.(type) {
	case *ActionLogEntry_CatchPokemon:
		s := proto.Size(x.CatchPokemon)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionLogEntry_FortSearch:
		s := proto.Size(x.FortSearch)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionLogEntry_BuddyPokemon:
		s := proto.Size(x.BuddyPokemon)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BuddyPokemonLogEntry struct {
	Result    BuddyPokemonLogEntry_Result `protobuf:"varint,1,opt,name=result,enum=POGOProtos.Data.Logs.BuddyPokemonLogEntry_Result" json:"result,omitempty"`
	PokemonId PokemonId                   `protobuf:"varint,2,opt,name=pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	Amount    int32                       `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
}

func (m *BuddyPokemonLogEntry) Reset()                    { *m = BuddyPokemonLogEntry{} }
func (m *BuddyPokemonLogEntry) String() string            { return proto.CompactTextString(m) }
func (*BuddyPokemonLogEntry) ProtoMessage()               {}
func (*BuddyPokemonLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{1} }

type FortSearchLogEntry struct {
	Result FortSearchLogEntry_Result `protobuf:"varint,1,opt,name=result,enum=POGOProtos.Data.Logs.FortSearchLogEntry_Result" json:"result,omitempty"`
	FortId string                    `protobuf:"bytes,2,opt,name=fort_id" json:"fort_id,omitempty"`
	Items  []*ItemData               `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	Eggs   int32                     `protobuf:"varint,4,opt,name=eggs" json:"eggs,omitempty"`
}

func (m *FortSearchLogEntry) Reset()                    { *m = FortSearchLogEntry{} }
func (m *FortSearchLogEntry) String() string            { return proto.CompactTextString(m) }
func (*FortSearchLogEntry) ProtoMessage()               {}
func (*FortSearchLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{2} }

func (m *FortSearchLogEntry) GetItems() []*ItemData {
	if m != nil {
		return m.Items
	}
	return nil
}

type CatchPokemonLogEntry struct {
	Result        CatchPokemonLogEntry_Result `protobuf:"varint,1,opt,name=result,enum=POGOProtos.Data.Logs.CatchPokemonLogEntry_Result" json:"result,omitempty"`
	PokemonId     PokemonId                   `protobuf:"varint,2,opt,name=pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	CombatPoints  int32                       `protobuf:"varint,3,opt,name=combat_points" json:"combat_points,omitempty"`
	PokemonDataId uint64                      `protobuf:"fixed64,4,opt,name=pokemon_data_id" json:"pokemon_data_id,omitempty"`
}

func (m *CatchPokemonLogEntry) Reset()                    { *m = CatchPokemonLogEntry{} }
func (m *CatchPokemonLogEntry) String() string            { return proto.CompactTextString(m) }
func (*CatchPokemonLogEntry) ProtoMessage()               {}
func (*CatchPokemonLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{3} }

func init() {
	proto.RegisterType((*ActionLogEntry)(nil), "POGOProtos.Data.Logs.ActionLogEntry")
	proto.RegisterType((*BuddyPokemonLogEntry)(nil), "POGOProtos.Data.Logs.BuddyPokemonLogEntry")
	proto.RegisterType((*FortSearchLogEntry)(nil), "POGOProtos.Data.Logs.FortSearchLogEntry")
	proto.RegisterType((*CatchPokemonLogEntry)(nil), "POGOProtos.Data.Logs.CatchPokemonLogEntry")
	proto.RegisterEnum("POGOProtos.Data.Logs.BuddyPokemonLogEntry_Result", BuddyPokemonLogEntry_Result_name, BuddyPokemonLogEntry_Result_value)
	proto.RegisterEnum("POGOProtos.Data.Logs.FortSearchLogEntry_Result", FortSearchLogEntry_Result_name, FortSearchLogEntry_Result_value)
	proto.RegisterEnum("POGOProtos.Data.Logs.CatchPokemonLogEntry_Result", CatchPokemonLogEntry_Result_name, CatchPokemonLogEntry_Result_value)
}

func init() { proto.RegisterFile("data_logs.proto", fileDescriptor21) }

var fileDescriptor21 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x5d, 0x8f, 0x9a, 0x40,
	0x14, 0x75, 0x74, 0x61, 0xdd, 0x8b, 0x1f, 0x64, 0x4a, 0x53, 0xb3, 0x7d, 0x31, 0xb4, 0x0f, 0xa6,
	0x0f, 0x6c, 0x6a, 0x7f, 0xc0, 0x46, 0x01, 0xab, 0xa9, 0x55, 0xb2, 0xe8, 0x43, 0xfb, 0x42, 0x46,
	0x60, 0x59, 0xd2, 0x85, 0x31, 0xcc, 0xd8, 0xc4, 0xbf, 0xd0, 0xf4, 0x47, 0xf5, 0xb9, 0xbf, 0xaa,
	0x61, 0x80, 0xc6, 0x74, 0x49, 0x63, 0xf6, 0x85, 0x90, 0x9b, 0x73, 0xcf, 0x3d, 0xf7, 0x9c, 0x3b,
	0xd0, 0x0f, 0x08, 0x27, 0xde, 0x23, 0x8d, 0x98, 0xb1, 0xcf, 0x28, 0xa7, 0x58, 0x73, 0xd6, 0x1f,
	0xd7, 0x4e, 0xfe, 0xcb, 0x0c, 0x8b, 0x70, 0x62, 0x2c, 0x69, 0xc4, 0xae, 0x95, 0x30, 0x3d, 0x24,
	0x25, 0xe4, 0x5a, 0x8b, 0xd3, 0xef, 0x61, 0xca, 0x69, 0x76, 0xf4, 0x62, 0x1e, 0x26, 0x45, 0x55,
	0xff, 0xd1, 0x84, 0xde, 0xc4, 0xe7, 0x31, 0x4d, 0x97, 0x34, 0xb2, 0x53, 0x9e, 0x1d, 0xb1, 0x06,
	0x1d, 0x1e, 0x27, 0x21, 0xe3, 0x24, 0xd9, 0x7b, 0x09, 0x1b, 0xa0, 0x21, 0x1a, 0xb5, 0x70, 0x17,
	0x24, 0x76, 0x1f, 0x07, 0x64, 0xd0, 0x1c, 0xa2, 0x51, 0x1b, 0x9b, 0xd0, 0xf5, 0x09, 0xf7, 0x1f,
	0xbc, 0x3d, 0xfd, 0x16, 0x26, 0x34, 0x1d, 0xb4, 0x86, 0x68, 0xa4, 0x8c, 0xdf, 0x19, 0x75, 0x42,
	0x0c, 0x33, 0x87, 0x3a, 0x05, 0xb2, 0x9a, 0x33, 0x6f, 0xe0, 0x5b, 0x50, 0xee, 0x69, 0xc6, 0x3d,
	0x16, 0x92, 0xcc, 0x7f, 0x18, 0x5c, 0x08, 0x8a, 0x51, 0x3d, 0xc5, 0x8c, 0x66, 0xdc, 0x15, 0xb8,
	0x13, 0x02, 0x13, 0xba, 0xbb, 0x43, 0x10, 0x1c, 0xff, 0xaa, 0x90, 0xfe, 0xa7, 0x62, 0x9a, 0x43,
	0x9f, 0xa8, 0x98, 0xb6, 0x41, 0x2e, 0x1c, 0xd0, 0x7f, 0x21, 0xd0, 0xea, 0x40, 0x78, 0x02, 0x72,
	0x16, 0xb2, 0xc3, 0x23, 0x17, 0x66, 0xf4, 0xc6, 0xef, 0xcf, 0x1f, 0x60, 0xdc, 0x89, 0x46, 0x7c,
	0x03, 0x50, 0x8a, 0xf4, 0xe2, 0x40, 0x98, 0xd8, 0x1b, 0xbf, 0x3e, 0xa5, 0xb1, 0x45, 0x56, 0x65,
	0xf7, 0x22, 0xc0, 0x3d, 0x90, 0x49, 0x42, 0x0f, 0x29, 0x17, 0xd6, 0x4a, 0xfa, 0x5b, 0x90, 0x4b,
	0xaa, 0x2b, 0x90, 0xb6, 0x2b, 0xd7, 0xde, 0xa8, 0x0d, 0xdc, 0x07, 0xc5, 0x9c, 0xac, 0xac, 0x2f,
	0xde, 0x6c, 0xbd, 0x5d, 0x59, 0x2a, 0xd2, 0x7f, 0x23, 0xc0, 0x4f, 0xad, 0xc2, 0xb7, 0xff, 0x2c,
	0x70, 0x73, 0xae, 0xc9, 0x95, 0xfc, 0x3e, 0x5c, 0x8a, 0xa8, 0x4a, 0xed, 0x57, 0x78, 0x0c, 0x52,
	0x7e, 0x46, 0x6c, 0xd0, 0x1a, 0xb6, 0x46, 0xca, 0xf8, 0xcd, 0x29, 0xe1, 0xa2, 0xba, 0x34, 0x63,
	0x91, 0x5f, 0x5a, 0xfe, 0xc9, 0x67, 0xe0, 0x0e, 0x5c, 0x84, 0x51, 0xc4, 0x44, 0xd0, 0x92, 0x3e,
	0xac, 0x5b, 0x48, 0x81, 0x4b, 0x77, 0x6b, 0x9a, 0xb6, 0xeb, 0xaa, 0x48, 0xff, 0xd9, 0x04, 0xad,
	0xee, 0x74, 0xce, 0xcd, 0xa3, 0xae, 0xf7, 0xd9, 0x79, 0xbc, 0x84, 0xae, 0x4f, 0x93, 0x1d, 0xe1,
	0xde, 0x9e, 0xc6, 0x29, 0x67, 0x45, 0x2c, 0xf8, 0x15, 0xf4, 0x2b, 0x1e, 0xf1, 0x28, 0xe3, 0x40,
	0xac, 0x27, 0xeb, 0x4e, 0xdd, 0x7a, 0x1a, 0xa8, 0xce, 0xfa, 0x93, 0xfd, 0x79, 0xbd, 0xf2, 0xcc,
	0x89, 0xb3, 0xd9, 0xde, 0xd9, 0x96, 0x8a, 0xb0, 0x0a, 0x9d, 0xaa, 0x3a, 0x5b, 0xda, 0x96, 0xda,
	0xc4, 0x2f, 0xa0, 0x5f, 0x55, 0xe6, 0x93, 0x8d, 0x39, 0xb7, 0x2d, 0xb5, 0x35, 0x6d, 0x7f, 0x95,
	0xc5, 0xa3, 0x65, 0x4e, 0xc3, 0x41, 0xbb, 0xe2, 0xff, 0xc3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x26, 0xfc, 0xae, 0x71, 0x0c, 0x04, 0x00, 0x00,
}
