// Code generated by protoc-gen-go.
// source: data_logs.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PokedexEntry from data.proto

// Ignoring public import of DownloadUrlEntry from data.proto

// Ignoring public import of PokemonDisplay from data.proto

// Ignoring public import of PlayerBadge from data.proto

// Ignoring public import of ClientVersion from data.proto

// Ignoring public import of PokemonData from data.proto

// Ignoring public import of PlayerData from data.proto

// Ignoring public import of BackgroundToken from data.proto

// Ignoring public import of AssetDigestEntry from data.proto

// Ignoring public import of BuddyPokemon from data.proto

// Ignoring public import of RedeemPasscodeReward from data.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

type BuddyPokemonLogEntry_Result int32

const (
	BuddyPokemonLogEntry_UNSET       BuddyPokemonLogEntry_Result = 0
	BuddyPokemonLogEntry_CANDY_FOUND BuddyPokemonLogEntry_Result = 1
)

var BuddyPokemonLogEntry_Result_name = map[int32]string{
	0: "UNSET",
	1: "CANDY_FOUND",
}
var BuddyPokemonLogEntry_Result_value = map[string]int32{
	"UNSET":       0,
	"CANDY_FOUND": 1,
}

func (x BuddyPokemonLogEntry_Result) String() string {
	return proto.EnumName(BuddyPokemonLogEntry_Result_name, int32(x))
}
func (BuddyPokemonLogEntry_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor22, []int{1, 0}
}

type FortSearchLogEntry_Result int32

const (
	FortSearchLogEntry_UNSET   FortSearchLogEntry_Result = 0
	FortSearchLogEntry_SUCCESS FortSearchLogEntry_Result = 1
)

var FortSearchLogEntry_Result_name = map[int32]string{
	0: "UNSET",
	1: "SUCCESS",
}
var FortSearchLogEntry_Result_value = map[string]int32{
	"UNSET":   0,
	"SUCCESS": 1,
}

func (x FortSearchLogEntry_Result) String() string {
	return proto.EnumName(FortSearchLogEntry_Result_name, int32(x))
}
func (FortSearchLogEntry_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor22, []int{2, 0}
}

type CatchPokemonLogEntry_Result int32

const (
	CatchPokemonLogEntry_UNSET            CatchPokemonLogEntry_Result = 0
	CatchPokemonLogEntry_POKEMON_CAPTURED CatchPokemonLogEntry_Result = 1
	CatchPokemonLogEntry_POKEMON_FLED     CatchPokemonLogEntry_Result = 2
	CatchPokemonLogEntry_POKEMON_HATCHED  CatchPokemonLogEntry_Result = 3
)

var CatchPokemonLogEntry_Result_name = map[int32]string{
	0: "UNSET",
	1: "POKEMON_CAPTURED",
	2: "POKEMON_FLED",
	3: "POKEMON_HATCHED",
}
var CatchPokemonLogEntry_Result_value = map[string]int32{
	"UNSET":            0,
	"POKEMON_CAPTURED": 1,
	"POKEMON_FLED":     2,
	"POKEMON_HATCHED":  3,
}

func (x CatchPokemonLogEntry_Result) String() string {
	return proto.EnumName(CatchPokemonLogEntry_Result_name, int32(x))
}
func (CatchPokemonLogEntry_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor22, []int{3, 0}
}

type ActionLogEntry struct {
	TimestampMs int64 `protobuf:"varint,1,opt,name=timestamp_ms" json:"timestamp_ms,omitempty"`
	Sfida       bool  `protobuf:"varint,2,opt,name=sfida" json:"sfida,omitempty"`
	// Types that are valid to be assigned to Action:
	//	*ActionLogEntry_CatchPokemon
	//	*ActionLogEntry_FortSearch
	//	*ActionLogEntry_BuddyPokemon
	Action isActionLogEntry_Action `protobuf_oneof:"Action"`
}

func (m *ActionLogEntry) Reset()                    { *m = ActionLogEntry{} }
func (m *ActionLogEntry) String() string            { return proto.CompactTextString(m) }
func (*ActionLogEntry) ProtoMessage()               {}
func (*ActionLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor22, []int{0} }

type isActionLogEntry_Action interface {
	isActionLogEntry_Action()
}

type ActionLogEntry_CatchPokemon struct {
	CatchPokemon *CatchPokemonLogEntry `protobuf:"bytes,3,opt,name=catch_pokemon,oneof"`
}
type ActionLogEntry_FortSearch struct {
	FortSearch *FortSearchLogEntry `protobuf:"bytes,4,opt,name=fort_search,oneof"`
}
type ActionLogEntry_BuddyPokemon struct {
	BuddyPokemon *BuddyPokemonLogEntry `protobuf:"bytes,5,opt,name=buddy_pokemon,oneof"`
}

func (*ActionLogEntry_CatchPokemon) isActionLogEntry_Action() {}
func (*ActionLogEntry_FortSearch) isActionLogEntry_Action()   {}
func (*ActionLogEntry_BuddyPokemon) isActionLogEntry_Action() {}

func (m *ActionLogEntry) GetAction() isActionLogEntry_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ActionLogEntry) GetCatchPokemon() *CatchPokemonLogEntry {
	if x, ok := m.GetAction().(*ActionLogEntry_CatchPokemon); ok {
		return x.CatchPokemon
	}
	return nil
}

func (m *ActionLogEntry) GetFortSearch() *FortSearchLogEntry {
	if x, ok := m.GetAction().(*ActionLogEntry_FortSearch); ok {
		return x.FortSearch
	}
	return nil
}

func (m *ActionLogEntry) GetBuddyPokemon() *BuddyPokemonLogEntry {
	if x, ok := m.GetAction().(*ActionLogEntry_BuddyPokemon); ok {
		return x.BuddyPokemon
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ActionLogEntry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ActionLogEntry_OneofMarshaler, _ActionLogEntry_OneofUnmarshaler, _ActionLogEntry_OneofSizer, []interface{}{
		(*ActionLogEntry_CatchPokemon)(nil),
		(*ActionLogEntry_FortSearch)(nil),
		(*ActionLogEntry_BuddyPokemon)(nil),
	}
}

func _ActionLogEntry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ActionLogEntry)
	// Action
	switch x := m.Action.(type) {
	case *ActionLogEntry_CatchPokemon:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CatchPokemon); err != nil {
			return err
		}
	case *ActionLogEntry_FortSearch:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FortSearch); err != nil {
			return err
		}
	case *ActionLogEntry_BuddyPokemon:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BuddyPokemon); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ActionLogEntry.Action has unexpected type %T", x)
	}
	return nil
}

func _ActionLogEntry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ActionLogEntry)
	switch tag {
	case 3: // Action.catch_pokemon
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CatchPokemonLogEntry)
		err := b.DecodeMessage(msg)
		m.Action = &ActionLogEntry_CatchPokemon{msg}
		return true, err
	case 4: // Action.fort_search
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FortSearchLogEntry)
		err := b.DecodeMessage(msg)
		m.Action = &ActionLogEntry_FortSearch{msg}
		return true, err
	case 5: // Action.buddy_pokemon
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BuddyPokemonLogEntry)
		err := b.DecodeMessage(msg)
		m.Action = &ActionLogEntry_BuddyPokemon{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ActionLogEntry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ActionLogEntry)
	// Action
	switch x := m.Action.(type) {
	case *ActionLogEntry_CatchPokemon:
		s := proto.Size(x.CatchPokemon)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionLogEntry_FortSearch:
		s := proto.Size(x.FortSearch)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionLogEntry_BuddyPokemon:
		s := proto.Size(x.BuddyPokemon)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BuddyPokemonLogEntry struct {
	Result         BuddyPokemonLogEntry_Result `protobuf:"varint,1,opt,name=result,enum=POGOProtos.Data.Logs.BuddyPokemonLogEntry_Result" json:"result,omitempty"`
	PokemonId      PokemonId                   `protobuf:"varint,2,opt,name=pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	Amount         int32                       `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	PokemonDisplay *PokemonDisplay             `protobuf:"bytes,4,opt,name=pokemon_display" json:"pokemon_display,omitempty"`
	Pokemon        uint64                      `protobuf:"fixed64,5,opt,name=pokemon" json:"pokemon,omitempty"`
}

func (m *BuddyPokemonLogEntry) Reset()                    { *m = BuddyPokemonLogEntry{} }
func (m *BuddyPokemonLogEntry) String() string            { return proto.CompactTextString(m) }
func (*BuddyPokemonLogEntry) ProtoMessage()               {}
func (*BuddyPokemonLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor22, []int{1} }

func (m *BuddyPokemonLogEntry) GetPokemonDisplay() *PokemonDisplay {
	if m != nil {
		return m.PokemonDisplay
	}
	return nil
}

type FortSearchLogEntry struct {
	Result      FortSearchLogEntry_Result `protobuf:"varint,1,opt,name=result,enum=POGOProtos.Data.Logs.FortSearchLogEntry_Result" json:"result,omitempty"`
	FortId      string                    `protobuf:"bytes,2,opt,name=fort_id" json:"fort_id,omitempty"`
	Items       []*ItemData               `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	Eggs        int32                     `protobuf:"varint,4,opt,name=eggs" json:"eggs,omitempty"`
	PokemonEggs []*PokemonData            `protobuf:"bytes,5,rep,name=pokemon_eggs" json:"pokemon_eggs,omitempty"`
}

func (m *FortSearchLogEntry) Reset()                    { *m = FortSearchLogEntry{} }
func (m *FortSearchLogEntry) String() string            { return proto.CompactTextString(m) }
func (*FortSearchLogEntry) ProtoMessage()               {}
func (*FortSearchLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor22, []int{2} }

func (m *FortSearchLogEntry) GetItems() []*ItemData {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *FortSearchLogEntry) GetPokemonEggs() []*PokemonData {
	if m != nil {
		return m.PokemonEggs
	}
	return nil
}

type CatchPokemonLogEntry struct {
	Result         CatchPokemonLogEntry_Result `protobuf:"varint,1,opt,name=result,enum=POGOProtos.Data.Logs.CatchPokemonLogEntry_Result" json:"result,omitempty"`
	PokemonId      PokemonId                   `protobuf:"varint,2,opt,name=pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	CombatPoints   int32                       `protobuf:"varint,3,opt,name=combat_points" json:"combat_points,omitempty"`
	PokemonDataId  uint64                      `protobuf:"fixed64,4,opt,name=pokemon_data_id" json:"pokemon_data_id,omitempty"`
	PokemonDisplay *PokemonDisplay             `protobuf:"bytes,5,opt,name=pokemon_display" json:"pokemon_display,omitempty"`
}

func (m *CatchPokemonLogEntry) Reset()                    { *m = CatchPokemonLogEntry{} }
func (m *CatchPokemonLogEntry) String() string            { return proto.CompactTextString(m) }
func (*CatchPokemonLogEntry) ProtoMessage()               {}
func (*CatchPokemonLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor22, []int{3} }

func (m *CatchPokemonLogEntry) GetPokemonDisplay() *PokemonDisplay {
	if m != nil {
		return m.PokemonDisplay
	}
	return nil
}

func init() {
	proto.RegisterType((*ActionLogEntry)(nil), "POGOProtos.Data.Logs.ActionLogEntry")
	proto.RegisterType((*BuddyPokemonLogEntry)(nil), "POGOProtos.Data.Logs.BuddyPokemonLogEntry")
	proto.RegisterType((*FortSearchLogEntry)(nil), "POGOProtos.Data.Logs.FortSearchLogEntry")
	proto.RegisterType((*CatchPokemonLogEntry)(nil), "POGOProtos.Data.Logs.CatchPokemonLogEntry")
	proto.RegisterEnum("POGOProtos.Data.Logs.BuddyPokemonLogEntry_Result", BuddyPokemonLogEntry_Result_name, BuddyPokemonLogEntry_Result_value)
	proto.RegisterEnum("POGOProtos.Data.Logs.FortSearchLogEntry_Result", FortSearchLogEntry_Result_name, FortSearchLogEntry_Result_value)
	proto.RegisterEnum("POGOProtos.Data.Logs.CatchPokemonLogEntry_Result", CatchPokemonLogEntry_Result_name, CatchPokemonLogEntry_Result_value)
}

func init() { proto.RegisterFile("data_logs.proto", fileDescriptor22) }

var fileDescriptor22 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x8f, 0x9a, 0x4e,
	0x18, 0xc6, 0x05, 0x17, 0x74, 0x5f, 0x54, 0xc8, 0xfc, 0xf9, 0xa7, 0x66, 0xdb, 0xa4, 0x86, 0xf6,
	0x60, 0x7a, 0x60, 0x53, 0x7a, 0xe9, 0x6d, 0xa3, 0x80, 0xd5, 0xd4, 0x2a, 0x59, 0xf5, 0xd0, 0x5e,
	0xc8, 0x28, 0xac, 0x4b, 0x2a, 0x8c, 0x61, 0xc6, 0x26, 0x7e, 0x85, 0xf6, 0x7b, 0xf5, 0x63, 0x35,
	0x0d, 0x23, 0x34, 0xa4, 0xd2, 0xc6, 0xf4, 0x62, 0xf0, 0xcd, 0xf3, 0x3e, 0xf3, 0xe4, 0x37, 0x4f,
	0x06, 0xd4, 0x00, 0x33, 0xec, 0xef, 0xc8, 0x96, 0x9a, 0xfb, 0x94, 0x30, 0x82, 0x74, 0x6f, 0xfe,
	0x6e, 0xee, 0x65, 0x9f, 0xd4, 0x74, 0x30, 0xc3, 0xe6, 0x94, 0x6c, 0xe9, 0x8d, 0x12, 0x26, 0x87,
	0x38, 0x97, 0xdc, 0x40, 0xb6, 0x93, 0x7f, 0xeb, 0x51, 0xf2, 0x25, 0x4c, 0x18, 0x49, 0x8f, 0x7e,
	0xc4, 0xc2, 0xf8, 0x34, 0x35, 0xbe, 0x8a, 0xd0, 0x19, 0x6c, 0x58, 0x44, 0x92, 0x29, 0xd9, 0xba,
	0x09, 0x4b, 0x8f, 0x48, 0x87, 0x16, 0x8b, 0xe2, 0x90, 0x32, 0x1c, 0xef, 0xfd, 0x98, 0x76, 0x85,
	0x9e, 0xd0, 0xaf, 0xa3, 0x36, 0x48, 0xf4, 0x21, 0x0a, 0x70, 0x57, 0xec, 0x09, 0xfd, 0x26, 0xb2,
	0xa1, 0xbd, 0xc1, 0x6c, 0xf3, 0xe8, 0xef, 0xc9, 0xe7, 0x30, 0x26, 0x49, 0xb7, 0xde, 0x13, 0xfa,
	0x8a, 0xf5, 0xca, 0xac, 0x0a, 0x65, 0xda, 0x99, 0xd4, 0x3b, 0x29, 0x8b, 0x73, 0xc6, 0x35, 0x74,
	0x07, 0xca, 0x03, 0x49, 0x99, 0x4f, 0x43, 0x9c, 0x6e, 0x1e, 0xbb, 0x57, 0xdc, 0xa2, 0x5f, 0x6d,
	0x31, 0x22, 0x29, 0x5b, 0x70, 0x5d, 0xc9, 0xc0, 0x86, 0xf6, 0xfa, 0x10, 0x04, 0xc7, 0x5f, 0x29,
	0xa4, 0xbf, 0xa5, 0x18, 0x66, 0xd2, 0xb3, 0x14, 0xc3, 0x26, 0xc8, 0x27, 0x02, 0xc6, 0x37, 0x11,
	0xf4, 0x2a, 0x11, 0x1a, 0x80, 0x9c, 0x86, 0xf4, 0xb0, 0x63, 0x1c, 0x46, 0xc7, 0x7a, 0x7d, 0xf9,
	0x01, 0xe6, 0x3d, 0x5f, 0x44, 0xb7, 0x00, 0x79, 0x48, 0x3f, 0x0a, 0x38, 0xc4, 0x8e, 0xf5, 0xb4,
	0x6c, 0xe3, 0xf2, 0x7b, 0xcb, 0xb7, 0x27, 0x01, 0xea, 0x80, 0x8c, 0x63, 0x72, 0x48, 0x18, 0x47,
	0x2b, 0xa1, 0xb7, 0xa0, 0x16, 0x06, 0x41, 0x44, 0xf7, 0x3b, 0x7c, 0xcc, 0x81, 0x3d, 0x3f, 0x0b,
	0x93, 0x9b, 0x38, 0x27, 0x19, 0x52, 0xa1, 0x51, 0xe6, 0x23, 0x1b, 0x2f, 0x41, 0xce, 0x53, 0x5d,
	0x83, 0xb4, 0x9a, 0x2d, 0xdc, 0xa5, 0x56, 0x43, 0x2a, 0x28, 0xf6, 0x60, 0xe6, 0x7c, 0xf4, 0x47,
	0xf3, 0xd5, 0xcc, 0xd1, 0x04, 0xe3, 0x87, 0x00, 0xe8, 0x9c, 0x3a, 0xba, 0xfb, 0x8d, 0xc5, 0xed,
	0xa5, 0xf7, 0x55, 0x90, 0x50, 0xa1, 0xc1, 0x6f, 0x3d, 0xc7, 0x70, 0x8d, 0x2c, 0x90, 0xb2, 0x46,
	0xd2, 0x6e, 0xbd, 0x57, 0xef, 0x2b, 0xd6, 0x8b, 0xb2, 0xe1, 0xa4, 0x28, 0xad, 0x39, 0xc9, 0x4a,
	0x9b, 0xfd, 0x64, 0x67, 0xa0, 0x16, 0x5c, 0x85, 0xdb, 0x2d, 0xe5, 0x08, 0x24, 0x64, 0x41, 0xab,
	0x60, 0xc3, 0xa7, 0x12, 0x37, 0x7a, 0xf6, 0x47, 0x30, 0x98, 0x61, 0xa3, 0x57, 0x05, 0x41, 0x81,
	0xc6, 0x62, 0x65, 0xdb, 0xee, 0x62, 0xa1, 0x09, 0xc6, 0x77, 0x11, 0xf4, 0xaa, 0xe6, 0x5e, 0x5a,
	0x87, 0xaa, 0xdd, 0x7f, 0xae, 0xc3, 0xff, 0xd0, 0xde, 0x90, 0x78, 0x8d, 0x99, 0xbf, 0x27, 0x51,
	0xc2, 0x68, 0xde, 0x8a, 0x27, 0xa5, 0x56, 0x64, 0xef, 0x43, 0x14, 0x70, 0x24, 0x72, 0x55, 0x5d,
	0xa4, 0x8b, 0xea, 0x62, 0x78, 0x55, 0x60, 0x74, 0xd0, 0xbc, 0xf9, 0x7b, 0xf7, 0xc3, 0x7c, 0xe6,
	0xdb, 0x03, 0x6f, 0xb9, 0xba, 0x77, 0x1d, 0x4d, 0x40, 0x1a, 0xb4, 0x8a, 0xe9, 0x68, 0xea, 0x3a,
	0x9a, 0x88, 0xfe, 0x03, 0xb5, 0x98, 0x8c, 0x07, 0x4b, 0x7b, 0xec, 0x3a, 0x5a, 0x7d, 0xd8, 0xfc,
	0x24, 0xf3, 0xd7, 0x86, 0x7a, 0x35, 0x4f, 0xf0, 0xc4, 0xf5, 0xe9, 0xdf, 0x9b, 0x9f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x96, 0xd4, 0xe6, 0xe8, 0xd3, 0x04, 0x00, 0x00,
}
