// Code generated by protoc-gen-go.
// source: map_pokemon.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of PokedexEntry from data.proto

// Ignoring public import of DownloadUrlEntry from data.proto

// Ignoring public import of PokemonDisplay from data.proto

// Ignoring public import of PlayerBadge from data.proto

// Ignoring public import of ClientVersion from data.proto

// Ignoring public import of PokemonData from data.proto

// Ignoring public import of PlayerData from data.proto

// Ignoring public import of BackgroundToken from data.proto

// Ignoring public import of AssetDigestEntry from data.proto

// Ignoring public import of BuddyPokemon from data.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

type WildPokemon struct {
	EncounterId             uint64       `protobuf:"fixed64,1,opt,name=encounter_id" json:"encounter_id,omitempty"`
	LastModifiedTimestampMs int64        `protobuf:"varint,2,opt,name=last_modified_timestamp_ms" json:"last_modified_timestamp_ms,omitempty"`
	Latitude                float64      `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude               float64      `protobuf:"fixed64,4,opt,name=longitude" json:"longitude,omitempty"`
	SpawnPointId            string       `protobuf:"bytes,5,opt,name=spawn_point_id" json:"spawn_point_id,omitempty"`
	PokemonData             *PokemonData `protobuf:"bytes,7,opt,name=pokemon_data" json:"pokemon_data,omitempty"`
	TimeTillHiddenMs        int32        `protobuf:"varint,11,opt,name=time_till_hidden_ms" json:"time_till_hidden_ms,omitempty"`
}

func (m *WildPokemon) Reset()                    { *m = WildPokemon{} }
func (m *WildPokemon) String() string            { return proto.CompactTextString(m) }
func (*WildPokemon) ProtoMessage()               {}
func (*WildPokemon) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

func (m *WildPokemon) GetPokemonData() *PokemonData {
	if m != nil {
		return m.PokemonData
	}
	return nil
}

type NearbyPokemon struct {
	PokemonId        PokemonId       `protobuf:"varint,1,opt,name=pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	DistanceInMeters float32         `protobuf:"fixed32,2,opt,name=distance_in_meters" json:"distance_in_meters,omitempty"`
	EncounterId      uint64          `protobuf:"fixed64,3,opt,name=encounter_id" json:"encounter_id,omitempty"`
	FortId           string          `protobuf:"bytes,4,opt,name=fort_id" json:"fort_id,omitempty"`
	FortImageUrl     string          `protobuf:"bytes,5,opt,name=fort_image_url" json:"fort_image_url,omitempty"`
	PokemonDisplay   *PokemonDisplay `protobuf:"bytes,6,opt,name=pokemon_display" json:"pokemon_display,omitempty"`
}

func (m *NearbyPokemon) Reset()                    { *m = NearbyPokemon{} }
func (m *NearbyPokemon) String() string            { return proto.CompactTextString(m) }
func (*NearbyPokemon) ProtoMessage()               {}
func (*NearbyPokemon) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

func (m *NearbyPokemon) GetPokemonDisplay() *PokemonDisplay {
	if m != nil {
		return m.PokemonDisplay
	}
	return nil
}

type MapPokemon struct {
	SpawnPointId string    `protobuf:"bytes,1,opt,name=spawn_point_id" json:"spawn_point_id,omitempty"`
	EncounterId  uint64    `protobuf:"fixed64,2,opt,name=encounter_id" json:"encounter_id,omitempty"`
	PokemonId    PokemonId `protobuf:"varint,3,opt,name=pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	// After this timestamp, the pokemon will be gone.
	ExpirationTimestampMs int64           `protobuf:"varint,4,opt,name=expiration_timestamp_ms" json:"expiration_timestamp_ms,omitempty"`
	Latitude              float64         `protobuf:"fixed64,5,opt,name=latitude" json:"latitude,omitempty"`
	Longitude             float64         `protobuf:"fixed64,6,opt,name=longitude" json:"longitude,omitempty"`
	PokemonDisplay        *PokemonDisplay `protobuf:"bytes,7,opt,name=pokemon_display" json:"pokemon_display,omitempty"`
}

func (m *MapPokemon) Reset()                    { *m = MapPokemon{} }
func (m *MapPokemon) String() string            { return proto.CompactTextString(m) }
func (*MapPokemon) ProtoMessage()               {}
func (*MapPokemon) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{2} }

func (m *MapPokemon) GetPokemonDisplay() *PokemonDisplay {
	if m != nil {
		return m.PokemonDisplay
	}
	return nil
}

func init() {
	proto.RegisterType((*WildPokemon)(nil), "POGOProtos.Map.Pokemon.WildPokemon")
	proto.RegisterType((*NearbyPokemon)(nil), "POGOProtos.Map.Pokemon.NearbyPokemon")
	proto.RegisterType((*MapPokemon)(nil), "POGOProtos.Map.Pokemon.MapPokemon")
}

func init() { proto.RegisterFile("map_pokemon.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x6e, 0xd4, 0x30,
	0x14, 0x85, 0xf1, 0x64, 0x26, 0xd3, 0xde, 0x94, 0x29, 0x35, 0x68, 0x88, 0x52, 0xa4, 0x46, 0xb3,
	0xca, 0x2a, 0x48, 0xc3, 0x86, 0x35, 0x02, 0x21, 0x16, 0xa5, 0xd9, 0x21, 0xb1, 0xb1, 0xdc, 0xda,
	0x2d, 0x16, 0xfe, 0x53, 0xec, 0x08, 0xfa, 0xa0, 0x3c, 0x05, 0x2f, 0x81, 0x6c, 0x67, 0xd0, 0x0c,
	0x01, 0xd1, 0xdd, 0xcd, 0xcd, 0x91, 0xce, 0xf9, 0xce, 0x35, 0x9c, 0x29, 0x6a, 0x89, 0x35, 0x5f,
	0xb9, 0x32, 0xba, 0xb5, 0xbd, 0xf1, 0x06, 0xaf, 0xbb, 0xab, 0xf7, 0x57, 0x5d, 0x18, 0x5d, 0x7b,
	0x49, 0x6d, 0xdb, 0xa5, 0xbf, 0x15, 0x30, 0xea, 0x69, 0xd2, 0x54, 0x05, 0xd7, 0x83, 0x72, 0xe9,
	0x63, 0xf3, 0x03, 0x41, 0xf1, 0x49, 0x48, 0x36, 0x0a, 0xf1, 0x33, 0x38, 0xe1, 0xfa, 0xc6, 0x0c,
	0xda, 0xf3, 0x9e, 0x08, 0x56, 0xa2, 0x1a, 0x35, 0x39, 0xde, 0x40, 0x25, 0xa9, 0xf3, 0x44, 0x19,
	0x26, 0x6e, 0x05, 0x67, 0xc4, 0x0b, 0xc5, 0x9d, 0xa7, 0xca, 0x12, 0xe5, 0xca, 0x59, 0x8d, 0x9a,
	0x0c, 0x3f, 0x81, 0x23, 0x49, 0xbd, 0xf0, 0x03, 0xe3, 0x65, 0x56, 0xa3, 0x06, 0xe1, 0x33, 0x38,
	0x96, 0x46, 0xdf, 0xa5, 0xd5, 0x3c, 0xae, 0xd6, 0xb0, 0x72, 0x96, 0x7e, 0xd3, 0xc4, 0x1a, 0xa1,
	0x7d, 0x30, 0x58, 0xd4, 0xa8, 0x39, 0xc6, 0x5b, 0x38, 0x19, 0x41, 0x48, 0x48, 0x5a, 0x2e, 0x6b,
	0xd4, 0x14, 0xdb, 0x17, 0xed, 0x1e, 0xce, 0xdb, 0x40, 0x30, 0xc6, 0x0c, 0x33, 0x3e, 0x87, 0xa7,
	0x21, 0x06, 0xf1, 0x42, 0x4a, 0xf2, 0x45, 0x30, 0xc6, 0x75, 0x48, 0x53, 0xd4, 0xa8, 0x59, 0x04,
	0xae, 0xc7, 0x1f, 0x39, 0xed, 0xaf, 0xef, 0x77, 0x64, 0x2f, 0x01, 0x76, 0x16, 0x23, 0xd7, 0x6a,
	0x7b, 0xbe, 0x6f, 0xf0, 0x2e, 0xd6, 0x32, 0xca, 0x3f, 0x30, 0x5c, 0x01, 0x66, 0xc2, 0x79, 0xaa,
	0x6f, 0x38, 0x11, 0x9a, 0x28, 0xee, 0x79, 0x9f, 0x60, 0x67, 0x93, 0x9a, 0xb2, 0x58, 0xd3, 0x29,
	0x2c, 0x6f, 0x4d, 0x1f, 0xb1, 0xe6, 0x11, 0x6b, 0x0d, 0xab, 0xb4, 0x50, 0xf4, 0x8e, 0x93, 0xa1,
	0x97, 0x23, 0xee, 0x6b, 0x38, 0xfd, 0x8d, 0x2b, 0x9c, 0x95, 0xf4, 0xbe, 0xcc, 0x23, 0xf1, 0xc5,
	0x3f, 0x89, 0x93, 0x6c, 0xf3, 0x13, 0x01, 0x5c, 0x52, 0xbb, 0x83, 0x9a, 0xf6, 0x89, 0xa2, 0xc1,
	0x9f, 0xf9, 0x66, 0x31, 0xdf, 0x61, 0x05, 0xd9, 0xff, 0x2b, 0xb8, 0x80, 0xe7, 0xfc, 0xbb, 0x15,
	0x3d, 0xf5, 0xc2, 0xe8, 0xc3, 0xa3, 0xcf, 0x27, 0x47, 0x5f, 0x4c, 0x8f, 0x9e, 0xc7, 0xd5, 0x5f,
	0x68, 0x97, 0x0f, 0xa2, 0x7d, 0x73, 0xf4, 0x39, 0x8f, 0xcf, 0xd4, 0x75, 0x8f, 0x3a, 0x74, 0x9d,
	0xe6, 0x57, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xd1, 0x24, 0xe5, 0xf8, 0x02, 0x00, 0x00,
}
