// Code generated by protoc-gen-go.
// source: networking_requests_messages.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of PlayerAvatarType from data_player.proto

// Ignoring public import of BattleAction from data_battle.proto

// Ignoring public import of BattleLog from data_battle.proto

// Ignoring public import of BattlePokemonInfo from data_battle.proto

// Ignoring public import of BattleParticipant from data_battle.proto

// Ignoring public import of BattleResults from data_battle.proto

// Ignoring public import of BattleState from data_battle.proto

// Ignoring public import of BattleActionType from data_battle.proto

// Ignoring public import of BattleType from data_battle.proto

type UseItemXpBoostMessage struct {
	ItemId ItemId `protobuf:"varint,1,opt,name=item_id,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
}

func (m *UseItemXpBoostMessage) Reset()                    { *m = UseItemXpBoostMessage{} }
func (m *UseItemXpBoostMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemXpBoostMessage) ProtoMessage()               {}
func (*UseItemXpBoostMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

type GetDownloadUrlsMessage struct {
	AssetId []string `protobuf:"bytes,1,rep,name=asset_id" json:"asset_id,omitempty"`
}

func (m *GetDownloadUrlsMessage) Reset()                    { *m = GetDownloadUrlsMessage{} }
func (m *GetDownloadUrlsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetDownloadUrlsMessage) ProtoMessage()               {}
func (*GetDownloadUrlsMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

type MarkTutorialCompleteMessage struct {
	TutorialsCompleted    []TutorialState `protobuf:"varint,1,rep,packed,name=tutorials_completed,enum=POGOProtos.Enums.TutorialState" json:"tutorials_completed,omitempty"`
	SendMarketingEmails   bool            `protobuf:"varint,2,opt,name=send_marketing_emails" json:"send_marketing_emails,omitempty"`
	SendPushNotifications bool            `protobuf:"varint,3,opt,name=send_push_notifications" json:"send_push_notifications,omitempty"`
}

func (m *MarkTutorialCompleteMessage) Reset()                    { *m = MarkTutorialCompleteMessage{} }
func (m *MarkTutorialCompleteMessage) String() string            { return proto.CompactTextString(m) }
func (*MarkTutorialCompleteMessage) ProtoMessage()               {}
func (*MarkTutorialCompleteMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

type SetFavoritePokemonMessage struct {
	PokemonId  int64 `protobuf:"varint,1,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
	IsFavorite bool  `protobuf:"varint,2,opt,name=is_favorite" json:"is_favorite,omitempty"`
}

func (m *SetFavoritePokemonMessage) Reset()                    { *m = SetFavoritePokemonMessage{} }
func (m *SetFavoritePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*SetFavoritePokemonMessage) ProtoMessage()               {}
func (*SetFavoritePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

type UseItemEggIncubatorMessage struct {
	ItemId    string `protobuf:"bytes,1,opt,name=item_id" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"varint,2,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
}

func (m *UseItemEggIncubatorMessage) Reset()                    { *m = UseItemEggIncubatorMessage{} }
func (m *UseItemEggIncubatorMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemEggIncubatorMessage) ProtoMessage()               {}
func (*UseItemEggIncubatorMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

type CheckAwardedBadgesMessage struct {
}

func (m *CheckAwardedBadgesMessage) Reset()                    { *m = CheckAwardedBadgesMessage{} }
func (m *CheckAwardedBadgesMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckAwardedBadgesMessage) ProtoMessage()               {}
func (*CheckAwardedBadgesMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{5} }

type IncenseEncounterMessage struct {
	EncounterId       uint64 `protobuf:"varint,1,opt,name=encounter_id" json:"encounter_id,omitempty"`
	EncounterLocation string `protobuf:"bytes,2,opt,name=encounter_location" json:"encounter_location,omitempty"`
}

func (m *IncenseEncounterMessage) Reset()                    { *m = IncenseEncounterMessage{} }
func (m *IncenseEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*IncenseEncounterMessage) ProtoMessage()               {}
func (*IncenseEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{6} }

type EquipBadgeMessage struct {
	BadgeType BadgeType `protobuf:"varint,1,opt,name=badge_type,enum=POGOProtos.Enums.BadgeType" json:"badge_type,omitempty"`
}

func (m *EquipBadgeMessage) Reset()                    { *m = EquipBadgeMessage{} }
func (m *EquipBadgeMessage) String() string            { return proto.CompactTextString(m) }
func (*EquipBadgeMessage) ProtoMessage()               {}
func (*EquipBadgeMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{7} }

type SetAvatarMessage struct {
	PlayerAvatar *PlayerAvatar `protobuf:"bytes,2,opt,name=player_avatar" json:"player_avatar,omitempty"`
}

func (m *SetAvatarMessage) Reset()                    { *m = SetAvatarMessage{} }
func (m *SetAvatarMessage) String() string            { return proto.CompactTextString(m) }
func (*SetAvatarMessage) ProtoMessage()               {}
func (*SetAvatarMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{8} }

func (m *SetAvatarMessage) GetPlayerAvatar() *PlayerAvatar {
	if m != nil {
		return m.PlayerAvatar
	}
	return nil
}

type EncounterMessage struct {
	EncounterId     uint64  `protobuf:"fixed64,1,opt,name=encounter_id" json:"encounter_id,omitempty"`
	SpawnPointId    string  `protobuf:"bytes,2,opt,name=spawn_point_id" json:"spawn_point_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *EncounterMessage) Reset()                    { *m = EncounterMessage{} }
func (m *EncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*EncounterMessage) ProtoMessage()               {}
func (*EncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{9} }

type FortDeployPokemonMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id" json:"fort_id,omitempty"`
	PokemonId       uint64  `protobuf:"fixed64,2,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *FortDeployPokemonMessage) Reset()                    { *m = FortDeployPokemonMessage{} }
func (m *FortDeployPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*FortDeployPokemonMessage) ProtoMessage()               {}
func (*FortDeployPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{10} }

type EncounterTutorialCompleteMessage struct {
	PokemonId PokemonId `protobuf:"varint,1,opt,name=pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
}

func (m *EncounterTutorialCompleteMessage) Reset()         { *m = EncounterTutorialCompleteMessage{} }
func (m *EncounterTutorialCompleteMessage) String() string { return proto.CompactTextString(m) }
func (*EncounterTutorialCompleteMessage) ProtoMessage()    {}
func (*EncounterTutorialCompleteMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{11}
}

type UseItemPotionMessage struct {
	ItemId    ItemId `protobuf:"varint,1,opt,name=item_id,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"fixed64,2,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
}

func (m *UseItemPotionMessage) Reset()                    { *m = UseItemPotionMessage{} }
func (m *UseItemPotionMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemPotionMessage) ProtoMessage()               {}
func (*UseItemPotionMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{12} }

type LevelUpRewardsMessage struct {
	Level int32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
}

func (m *LevelUpRewardsMessage) Reset()                    { *m = LevelUpRewardsMessage{} }
func (m *LevelUpRewardsMessage) String() string            { return proto.CompactTextString(m) }
func (*LevelUpRewardsMessage) ProtoMessage()               {}
func (*LevelUpRewardsMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{13} }

type ReleasePokemonMessage struct {
	PokemonId  uint64   `protobuf:"fixed64,1,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
	PokemonIds []uint64 `protobuf:"fixed64,2,rep,packed,name=pokemon_ids" json:"pokemon_ids,omitempty"`
}

func (m *ReleasePokemonMessage) Reset()                    { *m = ReleasePokemonMessage{} }
func (m *ReleasePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*ReleasePokemonMessage) ProtoMessage()               {}
func (*ReleasePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{14} }

type ListAvatarCustomizationsMessage struct {
	AvatarType PlayerAvatarType `protobuf:"varint,1,opt,name=avatar_type,enum=POGOProtos.Data.Player.PlayerAvatarType" json:"avatar_type,omitempty"`
	Slot       []Slot           `protobuf:"varint,2,rep,packed,name=slot,enum=POGOProtos.Enums.Slot" json:"slot,omitempty"`
	Filters    []Filter         `protobuf:"varint,3,rep,packed,name=filters,enum=POGOProtos.Enums.Filter" json:"filters,omitempty"`
	Start      int32            `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	Limit      int32            `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListAvatarCustomizationsMessage) Reset()         { *m = ListAvatarCustomizationsMessage{} }
func (m *ListAvatarCustomizationsMessage) String() string { return proto.CompactTextString(m) }
func (*ListAvatarCustomizationsMessage) ProtoMessage()    {}
func (*ListAvatarCustomizationsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{15}
}

type UpgradePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
}

func (m *UpgradePokemonMessage) Reset()                    { *m = UpgradePokemonMessage{} }
func (m *UpgradePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*UpgradePokemonMessage) ProtoMessage()               {}
func (*UpgradePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{16} }

type UseItemEncounterMessage struct {
	Item           ItemId `protobuf:"varint,1,opt,name=item,enum=POGOProtos.Inventory.Item.ItemId" json:"item,omitempty"`
	EncounterId    uint64 `protobuf:"fixed64,2,opt,name=encounter_id" json:"encounter_id,omitempty"`
	SpawnPointGuid string `protobuf:"bytes,3,opt,name=spawn_point_guid" json:"spawn_point_guid,omitempty"`
}

func (m *UseItemEncounterMessage) Reset()                    { *m = UseItemEncounterMessage{} }
func (m *UseItemEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemEncounterMessage) ProtoMessage()               {}
func (*UseItemEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{17} }

type UseItemReviveMessage struct {
	ItemId    ItemId `protobuf:"varint,1,opt,name=item_id,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"fixed64,2,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
}

func (m *UseItemReviveMessage) Reset()                    { *m = UseItemReviveMessage{} }
func (m *UseItemReviveMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemReviveMessage) ProtoMessage()               {}
func (*UseItemReviveMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{18} }

type FortDetailsMessage struct {
	FortId    string  `protobuf:"bytes,1,opt,name=fort_id" json:"fort_id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *FortDetailsMessage) Reset()                    { *m = FortDetailsMessage{} }
func (m *FortDetailsMessage) String() string            { return proto.CompactTextString(m) }
func (*FortDetailsMessage) ProtoMessage()               {}
func (*FortDetailsMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{19} }

type GetIncensePokemonMessage struct {
	PlayerLatitude  float64 `protobuf:"fixed64,1,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,2,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *GetIncensePokemonMessage) Reset()                    { *m = GetIncensePokemonMessage{} }
func (m *GetIncensePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*GetIncensePokemonMessage) ProtoMessage()               {}
func (*GetIncensePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{20} }

type CollectDailyBonusMessage struct {
}

func (m *CollectDailyBonusMessage) Reset()                    { *m = CollectDailyBonusMessage{} }
func (m *CollectDailyBonusMessage) String() string            { return proto.CompactTextString(m) }
func (*CollectDailyBonusMessage) ProtoMessage()               {}
func (*CollectDailyBonusMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{21} }

type DownloadSettingsMessage struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *DownloadSettingsMessage) Reset()                    { *m = DownloadSettingsMessage{} }
func (m *DownloadSettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*DownloadSettingsMessage) ProtoMessage()               {}
func (*DownloadSettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{22} }

type ClaimCodenameMessage struct {
	Codename string `protobuf:"bytes,1,opt,name=codename" json:"codename,omitempty"`
	Force    bool   `protobuf:"varint,2,opt,name=force" json:"force,omitempty"`
}

func (m *ClaimCodenameMessage) Reset()                    { *m = ClaimCodenameMessage{} }
func (m *ClaimCodenameMessage) String() string            { return proto.CompactTextString(m) }
func (*ClaimCodenameMessage) ProtoMessage()               {}
func (*ClaimCodenameMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{23} }

type AttackGymMessage struct {
	GymId               string          `protobuf:"bytes,1,opt,name=gym_id" json:"gym_id,omitempty"`
	BattleId            string          `protobuf:"bytes,2,opt,name=battle_id" json:"battle_id,omitempty"`
	AttackActions       []*BattleAction `protobuf:"bytes,3,rep,name=attack_actions" json:"attack_actions,omitempty"`
	LastRetrievedAction *BattleAction   `protobuf:"bytes,4,opt,name=last_retrieved_action" json:"last_retrieved_action,omitempty"`
	PlayerLatitude      float64         `protobuf:"fixed64,5,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude     float64         `protobuf:"fixed64,6,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *AttackGymMessage) Reset()                    { *m = AttackGymMessage{} }
func (m *AttackGymMessage) String() string            { return proto.CompactTextString(m) }
func (*AttackGymMessage) ProtoMessage()               {}
func (*AttackGymMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{24} }

func (m *AttackGymMessage) GetAttackActions() []*BattleAction {
	if m != nil {
		return m.AttackActions
	}
	return nil
}

func (m *AttackGymMessage) GetLastRetrievedAction() *BattleAction {
	if m != nil {
		return m.LastRetrievedAction
	}
	return nil
}

type FortSearchMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,2,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,3,opt,name=player_longitude" json:"player_longitude,omitempty"`
	FortLatitude    float64 `protobuf:"fixed64,4,opt,name=fort_latitude" json:"fort_latitude,omitempty"`
	FortLongitude   float64 `protobuf:"fixed64,5,opt,name=fort_longitude" json:"fort_longitude,omitempty"`
}

func (m *FortSearchMessage) Reset()                    { *m = FortSearchMessage{} }
func (m *FortSearchMessage) String() string            { return proto.CompactTextString(m) }
func (*FortSearchMessage) ProtoMessage()               {}
func (*FortSearchMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{25} }

type UseItemGymMessage struct {
	ItemId          ItemId  `protobuf:"varint,1,opt,name=item_id,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	GymId           string  `protobuf:"bytes,2,opt,name=gym_id" json:"gym_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *UseItemGymMessage) Reset()                    { *m = UseItemGymMessage{} }
func (m *UseItemGymMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemGymMessage) ProtoMessage()               {}
func (*UseItemGymMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{26} }

type SetContactSettingsMessage struct {
	ContactSettings *ContactSettings `protobuf:"bytes,1,opt,name=contact_settings" json:"contact_settings,omitempty"`
}

func (m *SetContactSettingsMessage) Reset()                    { *m = SetContactSettingsMessage{} }
func (m *SetContactSettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*SetContactSettingsMessage) ProtoMessage()               {}
func (*SetContactSettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{27} }

func (m *SetContactSettingsMessage) GetContactSettings() *ContactSettings {
	if m != nil {
		return m.ContactSettings
	}
	return nil
}

type CatchPokemonMessage struct {
	EncounterId           uint64  `protobuf:"fixed64,1,opt,name=encounter_id" json:"encounter_id,omitempty"`
	Pokeball              ItemId  `protobuf:"varint,2,opt,name=pokeball,enum=POGOProtos.Inventory.Item.ItemId" json:"pokeball,omitempty"`
	NormalizedReticleSize float64 `protobuf:"fixed64,3,opt,name=normalized_reticle_size" json:"normalized_reticle_size,omitempty"`
	SpawnPointId          string  `protobuf:"bytes,4,opt,name=spawn_point_id" json:"spawn_point_id,omitempty"`
	HitPokemon            bool    `protobuf:"varint,5,opt,name=hit_pokemon" json:"hit_pokemon,omitempty"`
	SpinModifier          float64 `protobuf:"fixed64,6,opt,name=spin_modifier" json:"spin_modifier,omitempty"`
	NormalizedHitPosition float64 `protobuf:"fixed64,7,opt,name=normalized_hit_position" json:"normalized_hit_position,omitempty"`
}

func (m *CatchPokemonMessage) Reset()                    { *m = CatchPokemonMessage{} }
func (m *CatchPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*CatchPokemonMessage) ProtoMessage()               {}
func (*CatchPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{28} }

type VerifyChallengeMessage struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *VerifyChallengeMessage) Reset()                    { *m = VerifyChallengeMessage{} }
func (m *VerifyChallengeMessage) String() string            { return proto.CompactTextString(m) }
func (*VerifyChallengeMessage) ProtoMessage()               {}
func (*VerifyChallengeMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{29} }

type SetBuddyPokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
}

func (m *SetBuddyPokemonMessage) Reset()                    { *m = SetBuddyPokemonMessage{} }
func (m *SetBuddyPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*SetBuddyPokemonMessage) ProtoMessage()               {}
func (*SetBuddyPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{30} }

type FortRecallPokemonMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id" json:"fort_id,omitempty"`
	PokemonId       uint64  `protobuf:"fixed64,2,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *FortRecallPokemonMessage) Reset()                    { *m = FortRecallPokemonMessage{} }
func (m *FortRecallPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*FortRecallPokemonMessage) ProtoMessage()               {}
func (*FortRecallPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{31} }

type EvolvePokemonMessage struct {
	PokemonId                uint64 `protobuf:"fixed64,1,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
	EvolutionItemRequirement ItemId `protobuf:"varint,2,opt,name=evolution_item_requirement,enum=POGOProtos.Inventory.Item.ItemId" json:"evolution_item_requirement,omitempty"`
}

func (m *EvolvePokemonMessage) Reset()                    { *m = EvolvePokemonMessage{} }
func (m *EvolvePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*EvolvePokemonMessage) ProtoMessage()               {}
func (*EvolvePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{32} }

type RecycleInventoryItemMessage struct {
	ItemId ItemId `protobuf:"varint,1,opt,name=item_id,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *RecycleInventoryItemMessage) Reset()                    { *m = RecycleInventoryItemMessage{} }
func (m *RecycleInventoryItemMessage) String() string            { return proto.CompactTextString(m) }
func (*RecycleInventoryItemMessage) ProtoMessage()               {}
func (*RecycleInventoryItemMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{33} }

type DownloadRemoteConfigVersionMessage struct {
	Platform           Platform `protobuf:"varint,1,opt,name=platform,enum=POGOProtos.Enums.Platform" json:"platform,omitempty"`
	DeviceManufacturer string   `protobuf:"bytes,2,opt,name=device_manufacturer" json:"device_manufacturer,omitempty"`
	DeviceModel        string   `protobuf:"bytes,3,opt,name=device_model" json:"device_model,omitempty"`
	Locale             string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	AppVersion         uint32   `protobuf:"varint,5,opt,name=app_version" json:"app_version,omitempty"`
}

func (m *DownloadRemoteConfigVersionMessage) Reset()         { *m = DownloadRemoteConfigVersionMessage{} }
func (m *DownloadRemoteConfigVersionMessage) String() string { return proto.CompactTextString(m) }
func (*DownloadRemoteConfigVersionMessage) ProtoMessage()    {}
func (*DownloadRemoteConfigVersionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{34}
}

type GetPlayerProfileMessage struct {
	PlayerName string `protobuf:"bytes,1,opt,name=player_name" json:"player_name,omitempty"`
}

func (m *GetPlayerProfileMessage) Reset()                    { *m = GetPlayerProfileMessage{} }
func (m *GetPlayerProfileMessage) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerProfileMessage) ProtoMessage()               {}
func (*GetPlayerProfileMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{35} }

type GetGymDetailsMessage struct {
	GymId           string  `protobuf:"bytes,1,opt,name=gym_id" json:"gym_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,2,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,3,opt,name=player_longitude" json:"player_longitude,omitempty"`
	GymLatitude     float64 `protobuf:"fixed64,4,opt,name=gym_latitude" json:"gym_latitude,omitempty"`
	GymLongitude    float64 `protobuf:"fixed64,5,opt,name=gym_longitude" json:"gym_longitude,omitempty"`
	ClientVersion   string  `protobuf:"bytes,6,opt,name=client_version" json:"client_version,omitempty"`
}

func (m *GetGymDetailsMessage) Reset()                    { *m = GetGymDetailsMessage{} }
func (m *GetGymDetailsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetGymDetailsMessage) ProtoMessage()               {}
func (*GetGymDetailsMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{36} }

type AddFortModifierMessage struct {
	ModifierType    ItemId  `protobuf:"varint,1,opt,name=modifier_type,enum=POGOProtos.Inventory.Item.ItemId" json:"modifier_type,omitempty"`
	FortId          string  `protobuf:"bytes,2,opt,name=fort_id" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *AddFortModifierMessage) Reset()                    { *m = AddFortModifierMessage{} }
func (m *AddFortModifierMessage) String() string            { return proto.CompactTextString(m) }
func (*AddFortModifierMessage) ProtoMessage()               {}
func (*AddFortModifierMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{37} }

type SetAvatarItemAsViewedMessage struct {
	AvatarTemplateId []string `protobuf:"bytes,1,rep,name=avatar_template_id" json:"avatar_template_id,omitempty"`
}

func (m *SetAvatarItemAsViewedMessage) Reset()                    { *m = SetAvatarItemAsViewedMessage{} }
func (m *SetAvatarItemAsViewedMessage) String() string            { return proto.CompactTextString(m) }
func (*SetAvatarItemAsViewedMessage) ProtoMessage()               {}
func (*SetAvatarItemAsViewedMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{38} }

type DownloadItemTemplatesMessage struct {
	Paginate      bool   `protobuf:"varint,1,opt,name=paginate" json:"paginate,omitempty"`
	PageOffset    int32  `protobuf:"varint,2,opt,name=page_offset" json:"page_offset,omitempty"`
	PageTimestamp uint64 `protobuf:"varint,3,opt,name=page_timestamp" json:"page_timestamp,omitempty"`
}

func (m *DownloadItemTemplatesMessage) Reset()                    { *m = DownloadItemTemplatesMessage{} }
func (m *DownloadItemTemplatesMessage) String() string            { return proto.CompactTextString(m) }
func (*DownloadItemTemplatesMessage) ProtoMessage()               {}
func (*DownloadItemTemplatesMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{39} }

type NicknamePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id" json:"pokemon_id,omitempty"`
	Nickname  string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
}

func (m *NicknamePokemonMessage) Reset()                    { *m = NicknamePokemonMessage{} }
func (m *NicknamePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*NicknamePokemonMessage) ProtoMessage()               {}
func (*NicknamePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{40} }

type CollectDailyDefenderBonusMessage struct {
}

func (m *CollectDailyDefenderBonusMessage) Reset()         { *m = CollectDailyDefenderBonusMessage{} }
func (m *CollectDailyDefenderBonusMessage) String() string { return proto.CompactTextString(m) }
func (*CollectDailyDefenderBonusMessage) ProtoMessage()    {}
func (*CollectDailyDefenderBonusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{41}
}

type GetAssetDigestMessage struct {
	Platform           Platform `protobuf:"varint,1,opt,name=platform,enum=POGOProtos.Enums.Platform" json:"platform,omitempty"`
	DeviceManufacturer string   `protobuf:"bytes,2,opt,name=device_manufacturer" json:"device_manufacturer,omitempty"`
	DeviceModel        string   `protobuf:"bytes,3,opt,name=device_model" json:"device_model,omitempty"`
	Locale             string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	AppVersion         uint32   `protobuf:"varint,5,opt,name=app_version" json:"app_version,omitempty"`
}

func (m *GetAssetDigestMessage) Reset()                    { *m = GetAssetDigestMessage{} }
func (m *GetAssetDigestMessage) String() string            { return proto.CompactTextString(m) }
func (*GetAssetDigestMessage) ProtoMessage()               {}
func (*GetAssetDigestMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{42} }

type GetBuddyWalkedMessage struct {
}

func (m *GetBuddyWalkedMessage) Reset()                    { *m = GetBuddyWalkedMessage{} }
func (m *GetBuddyWalkedMessage) String() string            { return proto.CompactTextString(m) }
func (*GetBuddyWalkedMessage) ProtoMessage()               {}
func (*GetBuddyWalkedMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{43} }

type RegisterBackgroundDeviceMessage struct {
	DeviceType string `protobuf:"bytes,1,opt,name=device_type" json:"device_type,omitempty"`
	DeviceId   string `protobuf:"bytes,2,opt,name=device_id" json:"device_id,omitempty"`
}

func (m *RegisterBackgroundDeviceMessage) Reset()         { *m = RegisterBackgroundDeviceMessage{} }
func (m *RegisterBackgroundDeviceMessage) String() string { return proto.CompactTextString(m) }
func (*RegisterBackgroundDeviceMessage) ProtoMessage()    {}
func (*RegisterBackgroundDeviceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{44}
}

type GetMapObjectsMessage struct {
	CellId           []uint64 `protobuf:"varint,1,rep,packed,name=cell_id" json:"cell_id,omitempty"`
	SinceTimestampMs []int64  `protobuf:"varint,2,rep,packed,name=since_timestamp_ms" json:"since_timestamp_ms,omitempty"`
	Latitude         float64  `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude        float64  `protobuf:"fixed64,4,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *GetMapObjectsMessage) Reset()                    { *m = GetMapObjectsMessage{} }
func (m *GetMapObjectsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetMapObjectsMessage) ProtoMessage()               {}
func (*GetMapObjectsMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{45} }

type StartGymBattleMessage struct {
	GymId               string   `protobuf:"bytes,1,opt,name=gym_id" json:"gym_id,omitempty"`
	AttackingPokemonIds []uint64 `protobuf:"fixed64,2,rep,packed,name=attacking_pokemon_ids" json:"attacking_pokemon_ids,omitempty"`
	DefendingPokemonId  uint64   `protobuf:"fixed64,3,opt,name=defending_pokemon_id" json:"defending_pokemon_id,omitempty"`
	PlayerLatitude      float64  `protobuf:"fixed64,4,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude     float64  `protobuf:"fixed64,5,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *StartGymBattleMessage) Reset()                    { *m = StartGymBattleMessage{} }
func (m *StartGymBattleMessage) String() string            { return proto.CompactTextString(m) }
func (*StartGymBattleMessage) ProtoMessage()               {}
func (*StartGymBattleMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{46} }

type EchoMessage struct {
}

func (m *EchoMessage) Reset()                    { *m = EchoMessage{} }
func (m *EchoMessage) String() string            { return proto.CompactTextString(m) }
func (*EchoMessage) ProtoMessage()               {}
func (*EchoMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{47} }

type GetHatchedEggsMessage struct {
}

func (m *GetHatchedEggsMessage) Reset()                    { *m = GetHatchedEggsMessage{} }
func (m *GetHatchedEggsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetHatchedEggsMessage) ProtoMessage()               {}
func (*GetHatchedEggsMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{48} }

type GetPlayerMessage struct {
	PlayerLocale *GetPlayerMessage_PlayerLocale `protobuf:"bytes,1,opt,name=player_locale" json:"player_locale,omitempty"`
}

func (m *GetPlayerMessage) Reset()                    { *m = GetPlayerMessage{} }
func (m *GetPlayerMessage) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerMessage) ProtoMessage()               {}
func (*GetPlayerMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{49} }

func (m *GetPlayerMessage) GetPlayerLocale() *GetPlayerMessage_PlayerLocale {
	if m != nil {
		return m.PlayerLocale
	}
	return nil
}

type GetPlayerMessage_PlayerLocale struct {
	Country  string `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	Timezone string `protobuf:"bytes,3,opt,name=timezone" json:"timezone,omitempty"`
}

func (m *GetPlayerMessage_PlayerLocale) Reset()         { *m = GetPlayerMessage_PlayerLocale{} }
func (m *GetPlayerMessage_PlayerLocale) String() string { return proto.CompactTextString(m) }
func (*GetPlayerMessage_PlayerLocale) ProtoMessage()    {}
func (*GetPlayerMessage_PlayerLocale) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{49, 0}
}

type GetInventoryMessage struct {
	LastTimestampMs int64 `protobuf:"varint,1,opt,name=last_timestamp_ms" json:"last_timestamp_ms,omitempty"`
	ItemBeenSeen    int32 `protobuf:"varint,2,opt,name=item_been_seen" json:"item_been_seen,omitempty"`
}

func (m *GetInventoryMessage) Reset()                    { *m = GetInventoryMessage{} }
func (m *GetInventoryMessage) String() string            { return proto.CompactTextString(m) }
func (*GetInventoryMessage) ProtoMessage()               {}
func (*GetInventoryMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{50} }

type SetPlayerTeamMessage struct {
	Team TeamColor `protobuf:"varint,1,opt,name=team,enum=POGOProtos.Enums.TeamColor" json:"team,omitempty"`
}

func (m *SetPlayerTeamMessage) Reset()                    { *m = SetPlayerTeamMessage{} }
func (m *SetPlayerTeamMessage) String() string            { return proto.CompactTextString(m) }
func (*SetPlayerTeamMessage) ProtoMessage()               {}
func (*SetPlayerTeamMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{51} }

type CheckChallengeMessage struct {
	DebugRequest bool `protobuf:"varint,1,opt,name=debug_request" json:"debug_request,omitempty"`
}

func (m *CheckChallengeMessage) Reset()                    { *m = CheckChallengeMessage{} }
func (m *CheckChallengeMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckChallengeMessage) ProtoMessage()               {}
func (*CheckChallengeMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{52} }

type UseItemCaptureMessage struct {
	ItemId       ItemId `protobuf:"varint,1,opt,name=item_id,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	EncounterId  uint64 `protobuf:"fixed64,2,opt,name=encounter_id" json:"encounter_id,omitempty"`
	SpawnPointId string `protobuf:"bytes,3,opt,name=spawn_point_id" json:"spawn_point_id,omitempty"`
}

func (m *UseItemCaptureMessage) Reset()                    { *m = UseItemCaptureMessage{} }
func (m *UseItemCaptureMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemCaptureMessage) ProtoMessage()               {}
func (*UseItemCaptureMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{53} }

type DiskEncounterMessage struct {
	EncounterId     uint64  `protobuf:"varint,1,opt,name=encounter_id" json:"encounter_id,omitempty"`
	FortId          string  `protobuf:"bytes,2,opt,name=fort_id" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude" json:"player_longitude,omitempty"`
}

func (m *DiskEncounterMessage) Reset()                    { *m = DiskEncounterMessage{} }
func (m *DiskEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*DiskEncounterMessage) ProtoMessage()               {}
func (*DiskEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{54} }

type UseIncenseMessage struct {
	IncenseType ItemId `protobuf:"varint,1,opt,name=incense_type,enum=POGOProtos.Inventory.Item.ItemId" json:"incense_type,omitempty"`
}

func (m *UseIncenseMessage) Reset()                    { *m = UseIncenseMessage{} }
func (m *UseIncenseMessage) String() string            { return proto.CompactTextString(m) }
func (*UseIncenseMessage) ProtoMessage()               {}
func (*UseIncenseMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{55} }

type SfidaActionLogMessage struct {
}

func (m *SfidaActionLogMessage) Reset()                    { *m = SfidaActionLogMessage{} }
func (m *SfidaActionLogMessage) String() string            { return proto.CompactTextString(m) }
func (*SfidaActionLogMessage) ProtoMessage()               {}
func (*SfidaActionLogMessage) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{56} }

func init() {
	proto.RegisterType((*UseItemXpBoostMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemXpBoostMessage")
	proto.RegisterType((*GetDownloadUrlsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetDownloadUrlsMessage")
	proto.RegisterType((*MarkTutorialCompleteMessage)(nil), "POGOProtos.Networking.Requests.Messages.MarkTutorialCompleteMessage")
	proto.RegisterType((*SetFavoritePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetFavoritePokemonMessage")
	proto.RegisterType((*UseItemEggIncubatorMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemEggIncubatorMessage")
	proto.RegisterType((*CheckAwardedBadgesMessage)(nil), "POGOProtos.Networking.Requests.Messages.CheckAwardedBadgesMessage")
	proto.RegisterType((*IncenseEncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.IncenseEncounterMessage")
	proto.RegisterType((*EquipBadgeMessage)(nil), "POGOProtos.Networking.Requests.Messages.EquipBadgeMessage")
	proto.RegisterType((*SetAvatarMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetAvatarMessage")
	proto.RegisterType((*EncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.EncounterMessage")
	proto.RegisterType((*FortDeployPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortDeployPokemonMessage")
	proto.RegisterType((*EncounterTutorialCompleteMessage)(nil), "POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage")
	proto.RegisterType((*UseItemPotionMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemPotionMessage")
	proto.RegisterType((*LevelUpRewardsMessage)(nil), "POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessage")
	proto.RegisterType((*ReleasePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.ReleasePokemonMessage")
	proto.RegisterType((*ListAvatarCustomizationsMessage)(nil), "POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage")
	proto.RegisterType((*UpgradePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.UpgradePokemonMessage")
	proto.RegisterType((*UseItemEncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemEncounterMessage")
	proto.RegisterType((*UseItemReviveMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemReviveMessage")
	proto.RegisterType((*FortDetailsMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortDetailsMessage")
	proto.RegisterType((*GetIncensePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetIncensePokemonMessage")
	proto.RegisterType((*CollectDailyBonusMessage)(nil), "POGOProtos.Networking.Requests.Messages.CollectDailyBonusMessage")
	proto.RegisterType((*DownloadSettingsMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadSettingsMessage")
	proto.RegisterType((*ClaimCodenameMessage)(nil), "POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage")
	proto.RegisterType((*AttackGymMessage)(nil), "POGOProtos.Networking.Requests.Messages.AttackGymMessage")
	proto.RegisterType((*FortSearchMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortSearchMessage")
	proto.RegisterType((*UseItemGymMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemGymMessage")
	proto.RegisterType((*SetContactSettingsMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetContactSettingsMessage")
	proto.RegisterType((*CatchPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.CatchPokemonMessage")
	proto.RegisterType((*VerifyChallengeMessage)(nil), "POGOProtos.Networking.Requests.Messages.VerifyChallengeMessage")
	proto.RegisterType((*SetBuddyPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetBuddyPokemonMessage")
	proto.RegisterType((*FortRecallPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortRecallPokemonMessage")
	proto.RegisterType((*EvolvePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.EvolvePokemonMessage")
	proto.RegisterType((*RecycleInventoryItemMessage)(nil), "POGOProtos.Networking.Requests.Messages.RecycleInventoryItemMessage")
	proto.RegisterType((*DownloadRemoteConfigVersionMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadRemoteConfigVersionMessage")
	proto.RegisterType((*GetPlayerProfileMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetPlayerProfileMessage")
	proto.RegisterType((*GetGymDetailsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetGymDetailsMessage")
	proto.RegisterType((*AddFortModifierMessage)(nil), "POGOProtos.Networking.Requests.Messages.AddFortModifierMessage")
	proto.RegisterType((*SetAvatarItemAsViewedMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetAvatarItemAsViewedMessage")
	proto.RegisterType((*DownloadItemTemplatesMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadItemTemplatesMessage")
	proto.RegisterType((*NicknamePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.NicknamePokemonMessage")
	proto.RegisterType((*CollectDailyDefenderBonusMessage)(nil), "POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage")
	proto.RegisterType((*GetAssetDigestMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetAssetDigestMessage")
	proto.RegisterType((*GetBuddyWalkedMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetBuddyWalkedMessage")
	proto.RegisterType((*RegisterBackgroundDeviceMessage)(nil), "POGOProtos.Networking.Requests.Messages.RegisterBackgroundDeviceMessage")
	proto.RegisterType((*GetMapObjectsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetMapObjectsMessage")
	proto.RegisterType((*StartGymBattleMessage)(nil), "POGOProtos.Networking.Requests.Messages.StartGymBattleMessage")
	proto.RegisterType((*EchoMessage)(nil), "POGOProtos.Networking.Requests.Messages.EchoMessage")
	proto.RegisterType((*GetHatchedEggsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetHatchedEggsMessage")
	proto.RegisterType((*GetPlayerMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetPlayerMessage")
	proto.RegisterType((*GetPlayerMessage_PlayerLocale)(nil), "POGOProtos.Networking.Requests.Messages.GetPlayerMessage.PlayerLocale")
	proto.RegisterType((*GetInventoryMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetInventoryMessage")
	proto.RegisterType((*SetPlayerTeamMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage")
	proto.RegisterType((*CheckChallengeMessage)(nil), "POGOProtos.Networking.Requests.Messages.CheckChallengeMessage")
	proto.RegisterType((*UseItemCaptureMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemCaptureMessage")
	proto.RegisterType((*DiskEncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.DiskEncounterMessage")
	proto.RegisterType((*UseIncenseMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseIncenseMessage")
	proto.RegisterType((*SfidaActionLogMessage)(nil), "POGOProtos.Networking.Requests.Messages.SfidaActionLogMessage")
}

func init() { proto.RegisterFile("networking_requests_messages.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 1909 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x58, 0xdd, 0x6e, 0x23, 0x49,
	0x15, 0xc6, 0x89, 0xf3, 0x77, 0x12, 0x67, 0x9d, 0x8e, 0x9d, 0x78, 0x9c, 0x59, 0x32, 0xb4, 0x56,
	0x4c, 0x16, 0x56, 0x1e, 0x29, 0x7b, 0xb1, 0x08, 0x16, 0x84, 0x63, 0x67, 0xb2, 0x61, 0x93, 0x1d,
	0x2b, 0x9e, 0x19, 0x10, 0xd2, 0x6e, 0x53, 0xe9, 0x3e, 0xee, 0x14, 0xae, 0xae, 0xea, 0xe9, 0x2a,
	0x3b, 0x72, 0x1e, 0x80, 0x0b, 0x1e, 0x00, 0x2e, 0x10, 0x3c, 0x00, 0x0f, 0xc0, 0x6b, 0xf0, 0x16,
	0xdc, 0xf0, 0x12, 0xa8, 0xaa, 0xba, 0xdb, 0x8e, 0x63, 0x83, 0xc9, 0xac, 0x10, 0x37, 0x93, 0x71,
	0xfd, 0x9c, 0x73, 0xea, 0x9c, 0xef, 0x3b, 0x3f, 0x0d, 0x2e, 0x47, 0x75, 0x2b, 0x92, 0x3e, 0xe5,
	0xa1, 0x97, 0xe0, 0xbb, 0x01, 0x4a, 0x25, 0xbd, 0x08, 0xa5, 0x24, 0x21, 0xca, 0x46, 0x9c, 0x08,
	0x25, 0x9c, 0xe7, 0x9d, 0x57, 0x67, 0xaf, 0x3a, 0xfa, 0xbf, 0xb2, 0xf1, 0x55, 0x7e, 0xbc, 0x71,
	0x95, 0x1e, 0x6f, 0x5c, 0xa6, 0xc7, 0xeb, 0x15, 0xca, 0x87, 0xc8, 0x95, 0x48, 0x46, 0x1e, 0x55,
	0x18, 0xd9, 0xeb, 0xf5, 0x4d, 0xe4, 0x83, 0x28, 0x95, 0x55, 0xdf, 0x09, 0x88, 0x22, 0x5e, 0xcc,
	0xc8, 0x08, 0x93, 0x7b, 0x4b, 0xd7, 0x44, 0x29, 0x86, 0x76, 0xc9, 0xfd, 0x12, 0xaa, 0x6f, 0x24,
	0x9e, 0x2b, 0x8c, 0x7e, 0x15, 0x9f, 0x08, 0x21, 0x55, 0xaa, 0xc2, 0x39, 0x86, 0x35, 0x2d, 0xd9,
	0xa3, 0x41, 0xad, 0xf0, 0xac, 0x70, 0xb4, 0x7d, 0xfc, 0xbd, 0xc6, 0x84, 0x71, 0xe7, 0x99, 0xfa,
	0x86, 0xbe, 0x6a, 0xfe, 0x39, 0x0f, 0xdc, 0x1f, 0xc0, 0xde, 0x19, 0xaa, 0xb6, 0xb8, 0xe5, 0x4c,
	0x90, 0xe0, 0x4d, 0xc2, 0x64, 0x26, 0xad, 0x0c, 0xeb, 0x44, 0x4a, 0x54, 0x56, 0xdc, 0xf2, 0xd1,
	0x86, 0xfb, 0xa7, 0x02, 0x1c, 0x5c, 0x92, 0xa4, 0xff, 0x7a, 0xa0, 0x44, 0x42, 0x09, 0x6b, 0x89,
	0x28, 0x66, 0xa8, 0x30, 0xbb, 0xf1, 0x39, 0xec, 0xaa, 0x74, 0x4b, 0x7a, 0x7e, 0xba, 0x69, 0x2f,
	0x6f, 0x1f, 0x1f, 0x4e, 0xda, 0x72, 0x6a, 0x1e, 0x9d, 0xc9, 0xe9, 0x2a, 0xa2, 0xd0, 0xf9, 0x10,
	0xaa, 0x12, 0x79, 0xe0, 0x45, 0x24, 0xe9, 0xa3, 0xd2, 0x2e, 0xc7, 0x88, 0x50, 0x26, 0x6b, 0x4b,
	0xcf, 0x0a, 0x47, 0xeb, 0xce, 0x21, 0xec, 0x9b, 0xed, 0x78, 0x20, 0x6f, 0x3c, 0x2e, 0x14, 0xed,
	0x51, 0x9f, 0x28, 0x2a, 0xb8, 0xac, 0x2d, 0xeb, 0x03, 0x6e, 0x1b, 0x9e, 0x74, 0x51, 0xbd, 0x24,
	0x43, 0x91, 0x50, 0x85, 0x1d, 0xd1, 0xc7, 0x48, 0xf0, 0xcc, 0x34, 0x07, 0x20, 0xb6, 0x2b, 0x99,
	0x77, 0x96, 0x9d, 0x5d, 0xd8, 0xa4, 0xd2, 0xeb, 0xa5, 0x17, 0xac, 0x1a, 0xb7, 0x09, 0xf5, 0xd4,
	0xb9, 0xa7, 0x61, 0x78, 0xce, 0xfd, 0xc1, 0x35, 0x51, 0x22, 0xc9, 0xc4, 0x7c, 0x70, 0xdf, 0xc3,
	0x1b, 0x53, 0x72, 0xb5, 0x88, 0xa2, 0x7b, 0x00, 0x4f, 0x5a, 0x37, 0xe8, 0xf7, 0x9b, 0xb7, 0x24,
	0x09, 0x30, 0x38, 0x21, 0x41, 0x88, 0x99, 0x57, 0xdd, 0x2f, 0x61, 0xff, 0x9c, 0xfb, 0xc8, 0x25,
	0x9e, 0x72, 0x5f, 0x0c, 0xb8, 0xc2, 0x5c, 0x78, 0x05, 0xb6, 0x30, 0x5b, 0xcb, 0x34, 0x14, 0x9d,
	0x3a, 0x38, 0xe3, 0x55, 0x26, 0xec, 0x9b, 0x8d, 0xa6, 0x0d, 0xb7, 0x0d, 0x3b, 0xa7, 0xef, 0x06,
	0x34, 0x36, 0x2a, 0x32, 0x31, 0x2f, 0x00, 0xae, 0xf5, 0x6f, 0x4f, 0x8d, 0x62, 0x4c, 0x81, 0x70,
	0xf0, 0xd0, 0xf9, 0xe6, 0xce, 0xeb, 0x51, 0x8c, 0xee, 0x2b, 0x28, 0x77, 0x51, 0x35, 0x87, 0x44,
	0x91, 0xdc, 0x96, 0x9f, 0x40, 0xc9, 0xc2, 0xd0, 0x23, 0x66, 0xdd, 0x28, 0xdc, 0x3c, 0xfe, 0x68,
	0x52, 0x4e, 0x9b, 0x28, 0xd2, 0xe8, 0x58, 0xb0, 0xda, 0x3f, 0x56, 0x86, 0x2b, 0xa1, 0xbc, 0xd0,
	0xe3, 0x56, 0x9d, 0x3d, 0xd8, 0x96, 0x31, 0xb9, 0xe5, 0x5e, 0x2c, 0x28, 0x57, 0x99, 0x0b, 0x37,
	0x9c, 0x7d, 0xf8, 0x20, 0x55, 0xcf, 0x88, 0xa2, 0x6a, 0x10, 0xa0, 0x09, 0x72, 0xc1, 0xa9, 0x41,
	0x39, 0xdb, 0x10, 0x3c, 0xb4, 0x3b, 0x45, 0xbd, 0xe3, 0x26, 0x50, 0x7b, 0x29, 0x12, 0xd5, 0xc6,
	0x98, 0x89, 0xd1, 0x54, 0xf4, 0x3f, 0x80, 0xb5, 0x9e, 0x48, 0xd4, 0xbf, 0x0b, 0xdb, 0xea, 0x63,
	0x74, 0x76, 0xe1, 0x59, 0xfe, 0xd0, 0x79, 0xa4, 0x78, 0xf1, 0x00, 0x79, 0x33, 0xc3, 0x91, 0x5a,
	0x7c, 0x1e, 0xb8, 0xdf, 0x40, 0x25, 0x45, 0x60, 0x47, 0xe8, 0x58, 0xbf, 0x07, 0xbb, 0x67, 0xbd,
	0xd3, 0xfd, 0x3e, 0x54, 0x2f, 0x70, 0x88, 0xec, 0x4d, 0x7c, 0x85, 0x1a, 0xa1, 0x39, 0xe1, 0x4b,
	0xb0, 0xc2, 0xf4, 0x86, 0x11, 0xbf, 0xe2, 0xfe, 0x1c, 0xaa, 0x57, 0xc8, 0x90, 0xc8, 0xff, 0xcc,
	0xa5, 0x55, 0xcd, 0xa5, 0xf1, 0x9a, 0xa6, 0xec, 0xf2, 0xd1, 0xaa, 0xfb, 0xf7, 0x02, 0x1c, 0x5e,
	0x50, 0x99, 0x42, 0xab, 0x35, 0x90, 0x4a, 0x44, 0xf4, 0xce, 0x92, 0x36, 0x13, 0xf6, 0x53, 0xd8,
	0xb4, 0x08, 0x9b, 0x84, 0xeb, 0xd1, 0x22, 0x30, 0xd3, 0xd8, 0x75, 0x3e, 0x82, 0xa2, 0x64, 0x42,
	0x19, 0x85, 0xdb, 0xc7, 0x7b, 0x0f, 0xfd, 0xda, 0x65, 0x42, 0x39, 0x1f, 0xc3, 0x5a, 0x8f, 0x32,
	0x85, 0x89, 0xce, 0x15, 0xfa, 0x60, 0xed, 0xe1, 0xc1, 0x97, 0xe6, 0x80, 0x76, 0x82, 0x54, 0x24,
	0x51, 0x26, 0xc2, 0x2b, 0xc6, 0x27, 0x34, 0xa2, 0xaa, 0xb6, 0x62, 0x7c, 0xf2, 0x43, 0xa8, 0xbe,
	0x89, 0xc3, 0x84, 0x04, 0x0b, 0xf8, 0xc4, 0xbd, 0x83, 0xfd, 0x2c, 0x95, 0x4c, 0xb3, 0xe1, 0x05,
	0x14, 0x75, 0x2c, 0x17, 0x0f, 0xe4, 0x34, 0x7d, 0x2c, 0x64, 0x6b, 0x50, 0x9e, 0xa4, 0x4f, 0x38,
	0xa0, 0x81, 0xc1, 0xec, 0xc6, 0x04, 0x88, 0xae, 0x70, 0x48, 0x87, 0xf8, 0x6d, 0x83, 0xe8, 0x17,
	0xe0, 0x58, 0xb6, 0x29, 0x9d, 0xa2, 0xe7, 0xf2, 0xac, 0x0c, 0xeb, 0x39, 0x99, 0x96, 0x0c, 0x99,
	0x76, 0x60, 0x63, 0xcc, 0x22, 0xc3, 0x2f, 0xf7, 0x12, 0x6a, 0x67, 0xa8, 0xd2, 0xac, 0x38, 0xe5,
	0xd7, 0x19, 0xa4, 0x2c, 0xcc, 0x25, 0xa5, 0xd1, 0xe0, 0xd6, 0xa1, 0xd6, 0x12, 0x8c, 0xa1, 0xaf,
	0xda, 0x84, 0xb2, 0xd1, 0x89, 0xe0, 0x83, 0x3c, 0xfb, 0x3e, 0x87, 0xfd, 0xac, 0xd4, 0x75, 0x51,
	0xe9, 0x22, 0x93, 0xdb, 0xbe, 0x05, 0xc5, 0x1b, 0x22, 0x6f, 0xac, 0xe1, 0xee, 0x67, 0x50, 0x69,
	0x31, 0x42, 0xa3, 0x96, 0x08, 0x90, 0x93, 0x08, 0x27, 0x8a, 0xa2, 0x9f, 0x2e, 0xa5, 0x4f, 0x2c,
	0xc1, 0x4a, 0x4f, 0x24, 0x7e, 0x56, 0x3f, 0xfe, 0x59, 0x80, 0x72, 0x53, 0x29, 0xe2, 0xf7, 0xcf,
	0x46, 0x51, 0x76, 0x6b, 0x1b, 0x56, 0xc3, 0xd1, 0x44, 0xd5, 0xd8, 0x81, 0x0d, 0x5b, 0xd1, 0xc7,
	0x19, 0xef, 0x73, 0xd8, 0x26, 0xe6, 0x9a, 0x47, 0xfc, 0xac, 0xaa, 0x2d, 0xcf, 0xcc, 0xb8, 0x27,
	0xb6, 0x17, 0xb0, 0x7f, 0x9a, 0xe6, 0xb0, 0xd3, 0x82, 0x2a, 0x23, 0x52, 0x79, 0x09, 0xaa, 0x84,
	0xe2, 0x10, 0x83, 0x54, 0x8a, 0x41, 0xf1, 0xa2, 0x42, 0x66, 0xf8, 0x7a, 0x65, 0xae, 0xaf, 0x57,
	0x8d, 0xaf, 0x7f, 0x57, 0x80, 0x1d, 0x8d, 0x83, 0x2e, 0x92, 0xc4, 0xbf, 0x99, 0x0b, 0x83, 0x19,
	0x92, 0x97, 0xe6, 0x4a, 0xb6, 0x49, 0xb7, 0x0a, 0x25, 0x23, 0x23, 0xbf, 0x60, 0x32, 0xae, 0x2e,
	0x18, 0x76, 0x39, 0x3f, 0x6e, 0x4c, 0x74, 0x7f, 0x5f, 0x80, 0x9d, 0x14, 0xf0, 0x13, 0x7e, 0x7f,
	0x0c, 0xda, 0xc7, 0xb1, 0x7a, 0x74, 0x29, 0xfa, 0xc6, 0x74, 0x22, 0x2d, 0xc1, 0x15, 0xf1, 0xd5,
	0x34, 0xce, 0x9a, 0x50, 0xf6, 0xed, 0x8e, 0x27, 0xd3, 0x2d, 0x63, 0xdc, 0xe6, 0xf1, 0xf3, 0x79,
	0x59, 0x6f, 0x4a, 0x92, 0xfb, 0x8f, 0x02, 0xec, 0xb6, 0x88, 0xf2, 0x6f, 0xa6, 0xc8, 0x32, 0xbb,
	0xc6, 0x7e, 0x0a, 0xeb, 0x9a, 0xbe, 0xd7, 0x84, 0x31, 0xf3, 0xa4, 0x85, 0xbc, 0x70, 0x08, 0xfb,
	0x5c, 0x24, 0x11, 0x61, 0xf4, 0x0e, 0x03, 0x0d, 0x2b, 0xea, 0x33, 0xf4, 0x24, 0xbd, 0xcb, 0x5e,
	0xff, 0xb0, 0x72, 0x17, 0x8d, 0xbb, 0x76, 0x61, 0xf3, 0x86, 0x2a, 0x2f, 0x4d, 0x18, 0x26, 0x3a,
	0xeb, 0x3a, 0x98, 0x32, 0xa6, 0xdc, 0x8b, 0x44, 0x40, 0x7b, 0x14, 0x13, 0x8b, 0x9e, 0x29, 0x25,
	0xf6, 0x9a, 0xa4, 0x06, 0xb7, 0x6b, 0xc6, 0x91, 0xcf, 0x61, 0xef, 0x2d, 0x26, 0xb4, 0x37, 0x6a,
	0xdd, 0x10, 0xc6, 0x90, 0x8f, 0x9b, 0x9c, 0x12, 0xac, 0x28, 0xd1, 0x47, 0x9e, 0xd2, 0xf5, 0x13,
	0xd8, 0xeb, 0xa2, 0x3a, 0x19, 0x04, 0xc1, 0x68, 0x81, 0xc4, 0x9c, 0xb6, 0x0a, 0x57, 0xe8, 0x13,
	0xc6, 0xfe, 0x47, 0xad, 0xc2, 0x3b, 0xa8, 0x9c, 0x0e, 0x05, 0x1b, 0x2e, 0x52, 0x4c, 0x4f, 0xa1,
	0x8e, 0x43, 0xc1, 0x06, 0xda, 0x13, 0x66, 0x56, 0x30, 0xc3, 0x07, 0x4d, 0x30, 0x42, 0xae, 0x16,
	0x8e, 0xa1, 0xfb, 0x1b, 0x38, 0xb8, 0x42, 0x7f, 0xe4, 0x33, 0xcc, 0xf7, 0xf5, 0xce, 0xfb, 0x90,
	0xa3, 0x04, 0x2b, 0x06, 0x5f, 0xc6, 0x88, 0x15, 0xf7, 0xaf, 0x05, 0x70, 0xb3, 0x7c, 0x7a, 0x85,
	0x91, 0x50, 0xd8, 0x12, 0xbc, 0x47, 0xc3, 0xb7, 0x98, 0xc8, 0x89, 0xce, 0xe5, 0x13, 0x58, 0x8f,
	0x19, 0x51, 0x3d, 0x91, 0x64, 0x15, 0xaf, 0x3e, 0xa3, 0x01, 0x4a, 0x4f, 0x38, 0x07, 0xb0, 0x1b,
	0xe0, 0x90, 0xfa, 0xe8, 0x45, 0x84, 0x0f, 0x7a, 0xc4, 0x57, 0x83, 0x04, 0x93, 0x94, 0x8d, 0x15,
	0xd8, 0xca, 0x36, 0x45, 0x80, 0xcc, 0x56, 0x3b, 0xcd, 0x59, 0xdd, 0x19, 0x33, 0x1c, 0x83, 0x90,
	0xc4, 0xb1, 0x37, 0xb4, 0x66, 0x18, 0x10, 0x96, 0xdc, 0x06, 0xec, 0x9f, 0xa1, 0xb2, 0x94, 0xea,
	0x24, 0xa2, 0x47, 0x59, 0x8e, 0x26, 0xdd, 0xbd, 0xd8, 0xb0, 0x8d, 0x13, 0xbb, 0xfb, 0x97, 0x02,
	0x54, 0xce, 0x50, 0x9d, 0x8d, 0xa2, 0xa9, 0x2a, 0x37, 0x9d, 0xcd, 0x1f, 0x91, 0xdd, 0x2a, 0xb0,
	0xa5, 0x45, 0x4c, 0x25, 0xb7, 0x2a, 0x94, 0xcc, 0xea, 0xfd, 0xdc, 0xa6, 0xa9, 0xe6, 0x33, 0x8a,
	0x5c, 0xe5, 0x0f, 0x5a, 0x35, 0x06, 0xfe, 0xa1, 0x00, 0x7b, 0xcd, 0x20, 0xd0, 0x50, 0xbe, 0x4c,
	0x89, 0x95, 0x99, 0xf8, 0x23, 0x28, 0x65, 0x5c, 0x9b, 0xec, 0xab, 0x16, 0x88, 0xf0, 0x04, 0xfe,
	0x1f, 0x9d, 0xff, 0x7e, 0x0c, 0x4f, 0xf3, 0x81, 0x42, 0x8b, 0x6d, 0xca, 0xb7, 0x14, 0x6f, 0x31,
	0xc8, 0xac, 0xab, 0x83, 0x93, 0xf5, 0x7c, 0x18, 0x69, 0x64, 0xe0, 0x78, 0xc6, 0xfc, 0x1a, 0x9e,
	0x66, 0x88, 0xd2, 0x57, 0x5f, 0xa7, 0x07, 0x26, 0xa7, 0xd2, 0x98, 0x84, 0x94, 0x13, 0x65, 0x1f,
	0xb5, 0x6e, 0x82, 0x47, 0x42, 0xf4, 0x44, 0xaf, 0x27, 0x31, 0x45, 0xa6, 0xf6, 0x99, 0x59, 0x54,
	0x34, 0x42, 0xa9, 0x48, 0x14, 0x1b, 0xa3, 0x8b, 0xee, 0xcf, 0x60, 0xef, 0x2b, 0xea, 0xf7, 0x75,
	0x98, 0x17, 0x20, 0x62, 0x19, 0xd6, 0x79, 0x7a, 0x3a, 0x9d, 0xb8, 0x5c, 0x78, 0x36, 0xd9, 0x5c,
	0xb4, 0xb1, 0x87, 0x3c, 0xc0, 0xe4, 0x5e, 0x93, 0xf1, 0xe7, 0x02, 0x54, 0xcf, 0x50, 0x35, 0xf5,
	0xf0, 0xdc, 0xa6, 0x21, 0x8e, 0x07, 0xf4, 0xff, 0x0f, 0x22, 0xec, 0x1b, 0xf3, 0x4c, 0xb2, 0xfc,
	0x25, 0x61, 0xfd, 0x3c, 0x2e, 0xee, 0x39, 0x1c, 0x5e, 0x61, 0x48, 0xa5, 0xc2, 0xe4, 0x84, 0xf8,
	0xfd, 0x30, 0x11, 0x03, 0x1e, 0xb4, 0x8d, 0x96, 0x09, 0xa6, 0xa4, 0x6a, 0x73, 0x58, 0x99, 0x76,
	0x26, 0x5d, 0xcc, 0x50, 0xe3, 0xc6, 0x86, 0x3b, 0x97, 0x24, 0x7e, 0x75, 0xfd, 0x5b, 0xf4, 0x95,
	0x1c, 0xdf, 0x5f, 0xf3, 0x91, 0xb1, 0x2c, 0xde, 0xc5, 0x93, 0xa5, 0x72, 0xc1, 0xf9, 0x2e, 0x38,
	0x92, 0x72, 0x7f, 0x22, 0x5a, 0x5e, 0x64, 0x67, 0x88, 0x65, 0xb3, 0x3f, 0xd9, 0x45, 0x2e, 0x3f,
	0xec, 0x22, 0x2d, 0xe8, 0xfe, 0x58, 0x80, 0x6a, 0x57, 0x77, 0xee, 0x67, 0xa3, 0xc8, 0xb6, 0x35,
	0xf3, 0xf8, 0xfa, 0x21, 0x54, 0x6d, 0xab, 0x45, 0x79, 0xe8, 0x3d, 0x98, 0x5a, 0x9c, 0xa7, 0x50,
	0x09, 0x4c, 0x58, 0xef, 0x6f, 0x1b, 0xcd, 0x33, 0x53, 0x7f, 0x71, 0x2e, 0x1d, 0x6c, 0x6f, 0x52,
	0x82, 0xcd, 0x53, 0xff, 0x46, 0x64, 0x5e, 0xb6, 0xee, 0xff, 0x42, 0xd7, 0x6f, 0x0c, 0x4e, 0xc3,
	0xbc, 0x33, 0x70, 0xff, 0x56, 0x80, 0x72, 0x9e, 0xa1, 0x32, 0xe3, 0xbf, 0xce, 0x07, 0xf1, 0x34,
	0xb0, 0xb6, 0x57, 0x78, 0xd9, 0x58, 0xf0, 0xb3, 0x53, 0x63, 0x5a, 0x62, 0xda, 0x54, 0x5c, 0x18,
	0x69, 0xf5, 0x16, 0x6c, 0x4d, 0xfe, 0xd6, 0xf4, 0x37, 0x09, 0x3e, 0x19, 0x4d, 0x76, 0xf0, 0x3c,
	0x1c, 0x90, 0x30, 0xa5, 0x80, 0x5e, 0xd1, 0x71, 0xba, 0x13, 0x1c, 0xd3, 0x61, 0xe3, 0x0b, 0xd8,
	0x35, 0x0d, 0x7c, 0x9a, 0x4f, 0x32, 0xd3, 0x9f, 0xc0, 0x8e, 0x69, 0x4a, 0xef, 0x45, 0xd5, 0x7e,
	0x7a, 0xd9, 0x83, 0x6d, 0x53, 0x7b, 0xae, 0x11, 0xb9, 0x27, 0x11, 0x79, 0x5a, 0x50, 0x9a, 0x50,
	0xe9, 0x66, 0xf6, 0xbe, 0x46, 0x92, 0xd7, 0xaa, 0x8f, 0xa1, 0xa8, 0x90, 0x44, 0xf3, 0xc7, 0x67,
	0x7d, 0xb8, 0x25, 0x98, 0x48, 0xdc, 0x06, 0x54, 0xcd, 0xd7, 0x97, 0x07, 0x2d, 0x43, 0x15, 0x4a,
	0x01, 0x5e, 0x0f, 0xf2, 0x2f, 0x79, 0x36, 0x7d, 0xb8, 0xa3, 0xfc, 0x6b, 0x5a, 0x8b, 0xc4, 0x9a,
	0x61, 0xef, 0x53, 0x1f, 0x67, 0x8f, 0x69, 0x0f, 0x7b, 0xa5, 0xe5, 0x8c, 0x24, 0x6d, 0x2a, 0xfb,
	0x0b, 0x7e, 0x08, 0xfa, 0x36, 0x32, 0xf3, 0x85, 0xed, 0x92, 0xed, 0xa8, 0x95, 0xa9, 0xfb, 0x0c,
	0xb6, 0xa8, 0x5d, 0xf9, 0xef, 0x6a, 0x85, 0x46, 0x72, 0xb7, 0x47, 0x03, 0x62, 0xe7, 0x87, 0x0b,
	0x11, 0xa6, 0x12, 0x4f, 0xd6, 0x7f, 0xbd, 0x6a, 0x3e, 0x55, 0xca, 0xce, 0x77, 0x3a, 0x85, 0xce,
	0x52, 0x67, 0xf9, 0xda, 0xfe, 0xfe, 0xf4, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xcd, 0x1f,
	0x70, 0x52, 0x15, 0x00, 0x00,
}
