// Code generated by protoc-gen-go.
// source: settings_master.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of DailyQuestSettings from settings_master_quest.proto

// Ignoring public import of BadgeCaptureReward from data_badge.proto

// Ignoring public import of CameraAttributes from settings_master_pokemon.proto

// Ignoring public import of EvolutionBranch from settings_master_pokemon.proto

// Ignoring public import of EncounterAttributes from settings_master_pokemon.proto

// Ignoring public import of StatsAttributes from settings_master_pokemon.proto

// Ignoring public import of BattleAttributes from settings_master_item.proto

// Ignoring public import of FortModifierAttributes from settings_master_item.proto

// Ignoring public import of FoodAttributes from settings_master_item.proto

// Ignoring public import of EggIncubatorAttributes from settings_master_item.proto

// Ignoring public import of InventoryUpgradeAttributes from settings_master_item.proto

// Ignoring public import of PokeballAttributes from settings_master_item.proto

// Ignoring public import of ReviveAttributes from settings_master_item.proto

// Ignoring public import of PotionAttributes from settings_master_item.proto

// Ignoring public import of IncenseAttributes from settings_master_item.proto

// Ignoring public import of ExperienceBoostAttributes from settings_master_item.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of PlayerAvatarType from data_player.proto

type PokemonSettings_BuddySize int32

const (
	PokemonSettings_BUDDY_MEDIUM   PokemonSettings_BuddySize = 0
	PokemonSettings_BUDDY_SHOULDER PokemonSettings_BuddySize = 1
	PokemonSettings_BUDDY_BIG      PokemonSettings_BuddySize = 2
	PokemonSettings_BUDDY_FLYING   PokemonSettings_BuddySize = 3
	PokemonSettings_BUDDY_BABY     PokemonSettings_BuddySize = 4
)

var PokemonSettings_BuddySize_name = map[int32]string{
	0: "BUDDY_MEDIUM",
	1: "BUDDY_SHOULDER",
	2: "BUDDY_BIG",
	3: "BUDDY_FLYING",
	4: "BUDDY_BABY",
}
var PokemonSettings_BuddySize_value = map[string]int32{
	"BUDDY_MEDIUM":   0,
	"BUDDY_SHOULDER": 1,
	"BUDDY_BIG":      2,
	"BUDDY_FLYING":   3,
	"BUDDY_BABY":     4,
}

func (x PokemonSettings_BuddySize) String() string {
	return proto.EnumName(PokemonSettings_BuddySize_name, int32(x))
}
func (PokemonSettings_BuddySize) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor18, []int{14, 0}
}

type AvatarCustomizationSettings_AvatarCustomizationPromoType int32

const (
	AvatarCustomizationSettings_UNSET_PROMO_TYPE AvatarCustomizationSettings_AvatarCustomizationPromoType = 0
	AvatarCustomizationSettings_SALE             AvatarCustomizationSettings_AvatarCustomizationPromoType = 1
	AvatarCustomizationSettings_FEATURED         AvatarCustomizationSettings_AvatarCustomizationPromoType = 2
)

var AvatarCustomizationSettings_AvatarCustomizationPromoType_name = map[int32]string{
	0: "UNSET_PROMO_TYPE",
	1: "SALE",
	2: "FEATURED",
}
var AvatarCustomizationSettings_AvatarCustomizationPromoType_value = map[string]int32{
	"UNSET_PROMO_TYPE": 0,
	"SALE":             1,
	"FEATURED":         2,
}

func (x AvatarCustomizationSettings_AvatarCustomizationPromoType) String() string {
	return proto.EnumName(AvatarCustomizationSettings_AvatarCustomizationPromoType_name, int32(x))
}
func (AvatarCustomizationSettings_AvatarCustomizationPromoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor18, []int{17, 0}
}

type AvatarCustomizationSettings_AvatarCustomizationUnlockType int32

const (
	AvatarCustomizationSettings_UNSET_UNLOCK_TYPE AvatarCustomizationSettings_AvatarCustomizationUnlockType = 0
	AvatarCustomizationSettings_DEFAULT           AvatarCustomizationSettings_AvatarCustomizationUnlockType = 1
	AvatarCustomizationSettings_MEDAL_REWARD      AvatarCustomizationSettings_AvatarCustomizationUnlockType = 2
	AvatarCustomizationSettings_IAP_CLOTHING      AvatarCustomizationSettings_AvatarCustomizationUnlockType = 3
)

var AvatarCustomizationSettings_AvatarCustomizationUnlockType_name = map[int32]string{
	0: "UNSET_UNLOCK_TYPE",
	1: "DEFAULT",
	2: "MEDAL_REWARD",
	3: "IAP_CLOTHING",
}
var AvatarCustomizationSettings_AvatarCustomizationUnlockType_value = map[string]int32{
	"UNSET_UNLOCK_TYPE": 0,
	"DEFAULT":           1,
	"MEDAL_REWARD":      2,
	"IAP_CLOTHING":      3,
}

func (x AvatarCustomizationSettings_AvatarCustomizationUnlockType) String() string {
	return proto.EnumName(AvatarCustomizationSettings_AvatarCustomizationUnlockType_name, int32(x))
}
func (AvatarCustomizationSettings_AvatarCustomizationUnlockType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor18, []int{17, 1}
}

type IapItemDisplay struct {
	Sku       string              `protobuf:"bytes,1,opt,name=sku" json:"sku,omitempty"`
	Category  HoloIapItemCategory `protobuf:"varint,2,opt,name=category,enum=POGOProtos.Enums.HoloIapItemCategory" json:"category,omitempty"`
	SortOrder int32               `protobuf:"varint,3,opt,name=sort_order" json:"sort_order,omitempty"`
	ItemIds   []ItemId            `protobuf:"varint,4,rep,packed,name=item_ids,enum=POGOProtos.Inventory.Item.ItemId" json:"item_ids,omitempty"`
	Counts    []int32             `protobuf:"varint,5,rep,packed,name=counts" json:"counts,omitempty"`
}

func (m *IapItemDisplay) Reset()                    { *m = IapItemDisplay{} }
func (m *IapItemDisplay) String() string            { return proto.CompactTextString(m) }
func (*IapItemDisplay) ProtoMessage()               {}
func (*IapItemDisplay) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{0} }

type IapSettings struct {
	DailyBonusCoins                int32    `protobuf:"varint,1,opt,name=daily_bonus_coins" json:"daily_bonus_coins,omitempty"`
	DailyDefenderBonusPerPokemon   []int32  `protobuf:"varint,2,rep,packed,name=daily_defender_bonus_per_pokemon" json:"daily_defender_bonus_per_pokemon,omitempty"`
	DailyDefenderBonusMaxDefenders int32    `protobuf:"varint,3,opt,name=daily_defender_bonus_max_defenders" json:"daily_defender_bonus_max_defenders,omitempty"`
	DailyDefenderBonusCurrency     []string `protobuf:"bytes,4,rep,name=daily_defender_bonus_currency" json:"daily_defender_bonus_currency,omitempty"`
	MinTimeBetweenClaimsMs         int64    `protobuf:"varint,5,opt,name=min_time_between_claims_ms" json:"min_time_between_claims_ms,omitempty"`
	DailyBonusEnabled              bool     `protobuf:"varint,6,opt,name=daily_bonus_enabled" json:"daily_bonus_enabled,omitempty"`
	DailyDefenderBonusEnabled      bool     `protobuf:"varint,7,opt,name=daily_defender_bonus_enabled" json:"daily_defender_bonus_enabled,omitempty"`
}

func (m *IapSettings) Reset()                    { *m = IapSettings{} }
func (m *IapSettings) String() string            { return proto.CompactTextString(m) }
func (*IapSettings) ProtoMessage()               {}
func (*IapSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{1} }

type MoveSettings struct {
	MovementId          PokemonMove `protobuf:"varint,1,opt,name=movement_id,enum=POGOProtos.Enums.PokemonMove" json:"movement_id,omitempty"`
	AnimationId         int32       `protobuf:"varint,2,opt,name=animation_id" json:"animation_id,omitempty"`
	PokemonType         PokemonType `protobuf:"varint,3,opt,name=pokemon_type,enum=POGOProtos.Enums.PokemonType" json:"pokemon_type,omitempty"`
	Power               float32     `protobuf:"fixed32,4,opt,name=power" json:"power,omitempty"`
	AccuracyChance      float32     `protobuf:"fixed32,5,opt,name=accuracy_chance" json:"accuracy_chance,omitempty"`
	CriticalChance      float32     `protobuf:"fixed32,6,opt,name=critical_chance" json:"critical_chance,omitempty"`
	HealScalar          float32     `protobuf:"fixed32,7,opt,name=heal_scalar" json:"heal_scalar,omitempty"`
	StaminaLossScalar   float32     `protobuf:"fixed32,8,opt,name=stamina_loss_scalar" json:"stamina_loss_scalar,omitempty"`
	TrainerLevelMin     int32       `protobuf:"varint,9,opt,name=trainer_level_min" json:"trainer_level_min,omitempty"`
	TrainerLevelMax     int32       `protobuf:"varint,10,opt,name=trainer_level_max" json:"trainer_level_max,omitempty"`
	VfxName             string      `protobuf:"bytes,11,opt,name=vfx_name" json:"vfx_name,omitempty"`
	DurationMs          int32       `protobuf:"varint,12,opt,name=duration_ms" json:"duration_ms,omitempty"`
	DamageWindowStartMs int32       `protobuf:"varint,13,opt,name=damage_window_start_ms" json:"damage_window_start_ms,omitempty"`
	DamageWindowEndMs   int32       `protobuf:"varint,14,opt,name=damage_window_end_ms" json:"damage_window_end_ms,omitempty"`
	EnergyDelta         int32       `protobuf:"varint,15,opt,name=energy_delta" json:"energy_delta,omitempty"`
}

func (m *MoveSettings) Reset()                    { *m = MoveSettings{} }
func (m *MoveSettings) String() string            { return proto.CompactTextString(m) }
func (*MoveSettings) ProtoMessage()               {}
func (*MoveSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{2} }

type QuestSettings struct {
	QuestType  QuestType           `protobuf:"varint,1,opt,name=quest_type,enum=POGOProtos.Enums.QuestType" json:"quest_type,omitempty"`
	DailyQuest *DailyQuestSettings `protobuf:"bytes,2,opt,name=daily_quest" json:"daily_quest,omitempty"`
}

func (m *QuestSettings) Reset()                    { *m = QuestSettings{} }
func (m *QuestSettings) String() string            { return proto.CompactTextString(m) }
func (*QuestSettings) ProtoMessage()               {}
func (*QuestSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{3} }

func (m *QuestSettings) GetDailyQuest() *DailyQuestSettings {
	if m != nil {
		return m.DailyQuest
	}
	return nil
}

type BadgeSettings struct {
	BadgeType     BadgeType             `protobuf:"varint,1,opt,name=badge_type,enum=POGOProtos.Enums.BadgeType" json:"badge_type,omitempty"`
	BadgeRank     int32                 `protobuf:"varint,2,opt,name=badge_rank" json:"badge_rank,omitempty"`
	Targets       []int32               `protobuf:"varint,3,rep,packed,name=targets" json:"targets,omitempty"`
	CaptureReward []*BadgeCaptureReward `protobuf:"bytes,4,rep,name=capture_reward" json:"capture_reward,omitempty"`
}

func (m *BadgeSettings) Reset()                    { *m = BadgeSettings{} }
func (m *BadgeSettings) String() string            { return proto.CompactTextString(m) }
func (*BadgeSettings) ProtoMessage()               {}
func (*BadgeSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{4} }

func (m *BadgeSettings) GetCaptureReward() []*BadgeCaptureReward {
	if m != nil {
		return m.CaptureReward
	}
	return nil
}

type EquippedBadgeSettings struct {
	EquipBadgeCooldownMs  int64     `protobuf:"varint,1,opt,name=equip_badge_cooldown_ms" json:"equip_badge_cooldown_ms,omitempty"`
	CatchProbabilityBonus []float32 `protobuf:"fixed32,2,rep,packed,name=catch_probability_bonus" json:"catch_probability_bonus,omitempty"`
	FleeProbabilityBonus  []float32 `protobuf:"fixed32,3,rep,packed,name=flee_probability_bonus" json:"flee_probability_bonus,omitempty"`
}

func (m *EquippedBadgeSettings) Reset()                    { *m = EquippedBadgeSettings{} }
func (m *EquippedBadgeSettings) String() string            { return proto.CompactTextString(m) }
func (*EquippedBadgeSettings) ProtoMessage()               {}
func (*EquippedBadgeSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{5} }

type TypeEffectiveSettings struct {
	AttackScalar []float32   `protobuf:"fixed32,1,rep,packed,name=attack_scalar" json:"attack_scalar,omitempty"`
	AttackType   PokemonType `protobuf:"varint,2,opt,name=attack_type,enum=POGOProtos.Enums.PokemonType" json:"attack_type,omitempty"`
}

func (m *TypeEffectiveSettings) Reset()                    { *m = TypeEffectiveSettings{} }
func (m *TypeEffectiveSettings) String() string            { return proto.CompactTextString(m) }
func (*TypeEffectiveSettings) ProtoMessage()               {}
func (*TypeEffectiveSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{6} }

type FormSettings struct {
	Pokemon PokemonId            `protobuf:"varint,1,opt,name=pokemon,enum=POGOProtos.Enums.PokemonId" json:"pokemon,omitempty"`
	Forms   []*FormSettings_Form `protobuf:"bytes,2,rep,name=forms" json:"forms,omitempty"`
}

func (m *FormSettings) Reset()                    { *m = FormSettings{} }
func (m *FormSettings) String() string            { return proto.CompactTextString(m) }
func (*FormSettings) ProtoMessage()               {}
func (*FormSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{7} }

func (m *FormSettings) GetForms() []*FormSettings_Form {
	if m != nil {
		return m.Forms
	}
	return nil
}

type FormSettings_Form struct {
	Form             Form  `protobuf:"varint,1,opt,name=form,enum=POGOProtos.Enums.Form" json:"form,omitempty"`
	AssetBundleValue int32 `protobuf:"varint,2,opt,name=asset_bundle_value" json:"asset_bundle_value,omitempty"`
}

func (m *FormSettings_Form) Reset()                    { *m = FormSettings_Form{} }
func (m *FormSettings_Form) String() string            { return proto.CompactTextString(m) }
func (*FormSettings_Form) ProtoMessage()               {}
func (*FormSettings_Form) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{7, 0} }

type CameraSettings struct {
	NextCamera        string                `protobuf:"bytes,1,opt,name=next_camera" json:"next_camera,omitempty"`
	Interpolation     []CameraInterpolation `protobuf:"varint,2,rep,packed,name=interpolation,enum=POGOProtos.Enums.CameraInterpolation" json:"interpolation,omitempty"`
	TargetType        []CameraTarget        `protobuf:"varint,3,rep,packed,name=target_type,enum=POGOProtos.Enums.CameraTarget" json:"target_type,omitempty"`
	EaseInSpeed       []float32             `protobuf:"fixed32,4,rep,packed,name=ease_in_speed" json:"ease_in_speed,omitempty"`
	EastOutSpeed      []float32             `protobuf:"fixed32,5,rep,packed,name=east_out_speed" json:"east_out_speed,omitempty"`
	DurationSeconds   []float32             `protobuf:"fixed32,6,rep,packed,name=duration_seconds" json:"duration_seconds,omitempty"`
	WaitSeconds       []float32             `protobuf:"fixed32,7,rep,packed,name=wait_seconds" json:"wait_seconds,omitempty"`
	TransitionSeconds []float32             `protobuf:"fixed32,8,rep,packed,name=transition_seconds" json:"transition_seconds,omitempty"`
	AngleDegree       []float32             `protobuf:"fixed32,9,rep,packed,name=angle_degree" json:"angle_degree,omitempty"`
	AngleOffsetDegree []float32             `protobuf:"fixed32,10,rep,packed,name=angle_offset_degree" json:"angle_offset_degree,omitempty"`
	PitchDegree       []float32             `protobuf:"fixed32,11,rep,packed,name=pitch_degree" json:"pitch_degree,omitempty"`
	PitchOffsetDegree []float32             `protobuf:"fixed32,12,rep,packed,name=pitch_offset_degree" json:"pitch_offset_degree,omitempty"`
	RollDegree        []float32             `protobuf:"fixed32,13,rep,packed,name=roll_degree" json:"roll_degree,omitempty"`
	DistanceMeters    []float32             `protobuf:"fixed32,14,rep,packed,name=distance_meters" json:"distance_meters,omitempty"`
	HeightPercent     []float32             `protobuf:"fixed32,15,rep,packed,name=height_percent" json:"height_percent,omitempty"`
	VertCtrRatio      []float32             `protobuf:"fixed32,16,rep,packed,name=vert_ctr_ratio" json:"vert_ctr_ratio,omitempty"`
}

func (m *CameraSettings) Reset()                    { *m = CameraSettings{} }
func (m *CameraSettings) String() string            { return proto.CompactTextString(m) }
func (*CameraSettings) ProtoMessage()               {}
func (*CameraSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{8} }

type GymLevelSettings struct {
	RequiredExperience []int32 `protobuf:"varint,1,rep,packed,name=required_experience" json:"required_experience,omitempty"`
	LeaderSlots        []int32 `protobuf:"varint,2,rep,packed,name=leader_slots" json:"leader_slots,omitempty"`
	TrainerSlots       []int32 `protobuf:"varint,3,rep,packed,name=trainer_slots" json:"trainer_slots,omitempty"`
	SearchRollBonus    []int32 `protobuf:"varint,4,rep,packed,name=search_roll_bonus" json:"search_roll_bonus,omitempty"`
}

func (m *GymLevelSettings) Reset()                    { *m = GymLevelSettings{} }
func (m *GymLevelSettings) String() string            { return proto.CompactTextString(m) }
func (*GymLevelSettings) ProtoMessage()               {}
func (*GymLevelSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{9} }

type MoveSequenceSettings struct {
	Sequence []string `protobuf:"bytes,1,rep,name=sequence" json:"sequence,omitempty"`
}

func (m *MoveSequenceSettings) Reset()                    { *m = MoveSequenceSettings{} }
func (m *MoveSequenceSettings) String() string            { return proto.CompactTextString(m) }
func (*MoveSequenceSettings) ProtoMessage()               {}
func (*MoveSequenceSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{10} }

type PlayerLevelSettings struct {
	RankNum                 []int32   `protobuf:"varint,1,rep,packed,name=rank_num" json:"rank_num,omitempty"`
	RequiredExperience      []int32   `protobuf:"varint,2,rep,packed,name=required_experience" json:"required_experience,omitempty"`
	CpMultiplier            []float32 `protobuf:"fixed32,3,rep,packed,name=cp_multiplier" json:"cp_multiplier,omitempty"`
	MaxEggPlayerLevel       int32     `protobuf:"varint,4,opt,name=max_egg_player_level" json:"max_egg_player_level,omitempty"`
	MaxEncounterPlayerLevel int32     `protobuf:"varint,5,opt,name=max_encounter_player_level" json:"max_encounter_player_level,omitempty"`
}

func (m *PlayerLevelSettings) Reset()                    { *m = PlayerLevelSettings{} }
func (m *PlayerLevelSettings) String() string            { return proto.CompactTextString(m) }
func (*PlayerLevelSettings) ProtoMessage()               {}
func (*PlayerLevelSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{11} }

type GymBattleSettings struct {
	EnergyPerSec                  float32 `protobuf:"fixed32,1,opt,name=energy_per_sec" json:"energy_per_sec,omitempty"`
	DodgeEnergyCost               float32 `protobuf:"fixed32,2,opt,name=dodge_energy_cost" json:"dodge_energy_cost,omitempty"`
	RetargetSeconds               float32 `protobuf:"fixed32,3,opt,name=retarget_seconds" json:"retarget_seconds,omitempty"`
	EnemyAttackInterval           float32 `protobuf:"fixed32,4,opt,name=enemy_attack_interval" json:"enemy_attack_interval,omitempty"`
	AttackServerInterval          float32 `protobuf:"fixed32,5,opt,name=attack_server_interval" json:"attack_server_interval,omitempty"`
	RoundDurationSeconds          float32 `protobuf:"fixed32,6,opt,name=round_duration_seconds" json:"round_duration_seconds,omitempty"`
	BonusTimePerAllySeconds       float32 `protobuf:"fixed32,7,opt,name=bonus_time_per_ally_seconds" json:"bonus_time_per_ally_seconds,omitempty"`
	MaximumAttackersPerBattle     int32   `protobuf:"varint,8,opt,name=maximum_attackers_per_battle" json:"maximum_attackers_per_battle,omitempty"`
	SameTypeAttackBonusMultiplier float32 `protobuf:"fixed32,9,opt,name=same_type_attack_bonus_multiplier" json:"same_type_attack_bonus_multiplier,omitempty"`
	MaximumEnergy                 int32   `protobuf:"varint,10,opt,name=maximum_energy" json:"maximum_energy,omitempty"`
	EnergyDeltaPerHealthLost      float32 `protobuf:"fixed32,11,opt,name=energy_delta_per_health_lost" json:"energy_delta_per_health_lost,omitempty"`
	DodgeDurationMs               int32   `protobuf:"varint,12,opt,name=dodge_duration_ms" json:"dodge_duration_ms,omitempty"`
	MinimumPlayerLevel            int32   `protobuf:"varint,13,opt,name=minimum_player_level" json:"minimum_player_level,omitempty"`
	SwapDurationMs                int32   `protobuf:"varint,14,opt,name=swap_duration_ms" json:"swap_duration_ms,omitempty"`
	DodgeDamageReductionPercent   float32 `protobuf:"fixed32,15,opt,name=dodge_damage_reduction_percent" json:"dodge_damage_reduction_percent,omitempty"`
}

func (m *GymBattleSettings) Reset()                    { *m = GymBattleSettings{} }
func (m *GymBattleSettings) String() string            { return proto.CompactTextString(m) }
func (*GymBattleSettings) ProtoMessage()               {}
func (*GymBattleSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{12} }

type PokemonUpgradeSettings struct {
	UpgradesPerLevel         int32   `protobuf:"varint,1,opt,name=upgrades_per_level" json:"upgrades_per_level,omitempty"`
	AllowedLevelsAbovePlayer int32   `protobuf:"varint,2,opt,name=allowed_levels_above_player" json:"allowed_levels_above_player,omitempty"`
	CandyCost                []int32 `protobuf:"varint,3,rep,packed,name=candy_cost" json:"candy_cost,omitempty"`
	StardustCost             []int32 `protobuf:"varint,4,rep,packed,name=stardust_cost" json:"stardust_cost,omitempty"`
}

func (m *PokemonUpgradeSettings) Reset()                    { *m = PokemonUpgradeSettings{} }
func (m *PokemonUpgradeSettings) String() string            { return proto.CompactTextString(m) }
func (*PokemonUpgradeSettings) ProtoMessage()               {}
func (*PokemonUpgradeSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{13} }

type PokemonSettings struct {
	PokemonId         PokemonId                 `protobuf:"varint,1,opt,name=pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
	ModelScale        float32                   `protobuf:"fixed32,3,opt,name=model_scale" json:"model_scale,omitempty"`
	Type              PokemonType               `protobuf:"varint,4,opt,name=type,enum=POGOProtos.Enums.PokemonType" json:"type,omitempty"`
	Type_2            PokemonType               `protobuf:"varint,5,opt,name=type_2,enum=POGOProtos.Enums.PokemonType" json:"type_2,omitempty"`
	Camera            *CameraAttributes         `protobuf:"bytes,6,opt,name=camera" json:"camera,omitempty"`
	Encounter         *EncounterAttributes      `protobuf:"bytes,7,opt,name=encounter" json:"encounter,omitempty"`
	Stats             *StatsAttributes          `protobuf:"bytes,8,opt,name=stats" json:"stats,omitempty"`
	QuickMoves        []PokemonMove             `protobuf:"varint,9,rep,packed,name=quick_moves,enum=POGOProtos.Enums.PokemonMove" json:"quick_moves,omitempty"`
	CinematicMoves    []PokemonMove             `protobuf:"varint,10,rep,packed,name=cinematic_moves,enum=POGOProtos.Enums.PokemonMove" json:"cinematic_moves,omitempty"`
	AnimationTime     []float32                 `protobuf:"fixed32,11,rep,packed,name=animation_time" json:"animation_time,omitempty"`
	EvolutionIds      []PokemonId               `protobuf:"varint,12,rep,packed,name=evolution_ids,enum=POGOProtos.Enums.PokemonId" json:"evolution_ids,omitempty"`
	EvolutionPips     int32                     `protobuf:"varint,13,opt,name=evolution_pips" json:"evolution_pips,omitempty"`
	Rarity            PokemonRarity             `protobuf:"varint,14,opt,name=rarity,enum=POGOProtos.Enums.PokemonRarity" json:"rarity,omitempty"`
	PokedexHeightM    float32                   `protobuf:"fixed32,15,opt,name=pokedex_height_m" json:"pokedex_height_m,omitempty"`
	PokedexWeightKg   float32                   `protobuf:"fixed32,16,opt,name=pokedex_weight_kg" json:"pokedex_weight_kg,omitempty"`
	ParentPokemonId   PokemonId                 `protobuf:"varint,17,opt,name=parent_pokemon_id,enum=POGOProtos.Enums.PokemonId" json:"parent_pokemon_id,omitempty"`
	HeightStdDev      float32                   `protobuf:"fixed32,18,opt,name=height_std_dev" json:"height_std_dev,omitempty"`
	WeightStdDev      float32                   `protobuf:"fixed32,19,opt,name=weight_std_dev" json:"weight_std_dev,omitempty"`
	KmDistanceToHatch float32                   `protobuf:"fixed32,20,opt,name=km_distance_to_hatch" json:"km_distance_to_hatch,omitempty"`
	FamilyId          PokemonFamilyId           `protobuf:"varint,21,opt,name=family_id,enum=POGOProtos.Enums.PokemonFamilyId" json:"family_id,omitempty"`
	CandyToEvolve     int32                     `protobuf:"varint,22,opt,name=candy_to_evolve" json:"candy_to_evolve,omitempty"`
	KmBuddyDistance   float32                   `protobuf:"fixed32,23,opt,name=km_buddy_distance" json:"km_buddy_distance,omitempty"`
	BuddySize         PokemonSettings_BuddySize `protobuf:"varint,24,opt,name=buddy_size,enum=POGOProtos.Settings.Master.PokemonSettings_BuddySize" json:"buddy_size,omitempty"`
	ModelHeight       float32                   `protobuf:"fixed32,25,opt,name=model_height" json:"model_height,omitempty"`
	EvolutionBranch   []*EvolutionBranch        `protobuf:"bytes,26,rep,name=evolution_branch" json:"evolution_branch,omitempty"`
}

func (m *PokemonSettings) Reset()                    { *m = PokemonSettings{} }
func (m *PokemonSettings) String() string            { return proto.CompactTextString(m) }
func (*PokemonSettings) ProtoMessage()               {}
func (*PokemonSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{14} }

func (m *PokemonSettings) GetCamera() *CameraAttributes {
	if m != nil {
		return m.Camera
	}
	return nil
}

func (m *PokemonSettings) GetEncounter() *EncounterAttributes {
	if m != nil {
		return m.Encounter
	}
	return nil
}

func (m *PokemonSettings) GetStats() *StatsAttributes {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *PokemonSettings) GetEvolutionBranch() []*EvolutionBranch {
	if m != nil {
		return m.EvolutionBranch
	}
	return nil
}

type ItemSettings struct {
	ItemId           ItemId                      `protobuf:"varint,1,opt,name=item_id,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	ItemType         ItemType                    `protobuf:"varint,2,opt,name=item_type,enum=POGOProtos.Inventory.Item.ItemType" json:"item_type,omitempty"`
	Category         ItemCategory                `protobuf:"varint,3,opt,name=category,enum=POGOProtos.Enums.ItemCategory" json:"category,omitempty"`
	DropFreq         float32                     `protobuf:"fixed32,4,opt,name=drop_freq" json:"drop_freq,omitempty"`
	DropTrainerLevel int32                       `protobuf:"varint,5,opt,name=drop_trainer_level" json:"drop_trainer_level,omitempty"`
	Pokeball         *PokeballAttributes         `protobuf:"bytes,6,opt,name=pokeball" json:"pokeball,omitempty"`
	Potion           *PotionAttributes           `protobuf:"bytes,7,opt,name=potion" json:"potion,omitempty"`
	Revive           *ReviveAttributes           `protobuf:"bytes,8,opt,name=revive" json:"revive,omitempty"`
	Battle           *BattleAttributes           `protobuf:"bytes,9,opt,name=battle" json:"battle,omitempty"`
	Food             *FoodAttributes             `protobuf:"bytes,10,opt,name=food" json:"food,omitempty"`
	InventoryUpgrade *InventoryUpgradeAttributes `protobuf:"bytes,11,opt,name=inventory_upgrade" json:"inventory_upgrade,omitempty"`
	XpBoost          *ExperienceBoostAttributes  `protobuf:"bytes,12,opt,name=xp_boost" json:"xp_boost,omitempty"`
	Incense          *IncenseAttributes          `protobuf:"bytes,13,opt,name=incense" json:"incense,omitempty"`
	EggIncubator     *EggIncubatorAttributes     `protobuf:"bytes,14,opt,name=egg_incubator" json:"egg_incubator,omitempty"`
	FortModifier     *FortModifierAttributes     `protobuf:"bytes,15,opt,name=fort_modifier" json:"fort_modifier,omitempty"`
}

func (m *ItemSettings) Reset()                    { *m = ItemSettings{} }
func (m *ItemSettings) String() string            { return proto.CompactTextString(m) }
func (*ItemSettings) ProtoMessage()               {}
func (*ItemSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{15} }

func (m *ItemSettings) GetPokeball() *PokeballAttributes {
	if m != nil {
		return m.Pokeball
	}
	return nil
}

func (m *ItemSettings) GetPotion() *PotionAttributes {
	if m != nil {
		return m.Potion
	}
	return nil
}

func (m *ItemSettings) GetRevive() *ReviveAttributes {
	if m != nil {
		return m.Revive
	}
	return nil
}

func (m *ItemSettings) GetBattle() *BattleAttributes {
	if m != nil {
		return m.Battle
	}
	return nil
}

func (m *ItemSettings) GetFood() *FoodAttributes {
	if m != nil {
		return m.Food
	}
	return nil
}

func (m *ItemSettings) GetInventoryUpgrade() *InventoryUpgradeAttributes {
	if m != nil {
		return m.InventoryUpgrade
	}
	return nil
}

func (m *ItemSettings) GetXpBoost() *ExperienceBoostAttributes {
	if m != nil {
		return m.XpBoost
	}
	return nil
}

func (m *ItemSettings) GetIncense() *IncenseAttributes {
	if m != nil {
		return m.Incense
	}
	return nil
}

func (m *ItemSettings) GetEggIncubator() *EggIncubatorAttributes {
	if m != nil {
		return m.EggIncubator
	}
	return nil
}

func (m *ItemSettings) GetFortModifier() *FortModifierAttributes {
	if m != nil {
		return m.FortModifier
	}
	return nil
}

type EncounterSettings struct {
	SpinBonusThreshold      float32 `protobuf:"fixed32,1,opt,name=spin_bonus_threshold" json:"spin_bonus_threshold,omitempty"`
	ExcellentThrowThreshold float32 `protobuf:"fixed32,2,opt,name=excellent_throw_threshold" json:"excellent_throw_threshold,omitempty"`
	GreatThrowThreshold     float32 `protobuf:"fixed32,3,opt,name=great_throw_threshold" json:"great_throw_threshold,omitempty"`
	NiceThrowThreshold      float32 `protobuf:"fixed32,4,opt,name=nice_throw_threshold" json:"nice_throw_threshold,omitempty"`
	MilestoneThreshold      int32   `protobuf:"varint,5,opt,name=milestone_threshold" json:"milestone_threshold,omitempty"`
}

func (m *EncounterSettings) Reset()                    { *m = EncounterSettings{} }
func (m *EncounterSettings) String() string            { return proto.CompactTextString(m) }
func (*EncounterSettings) ProtoMessage()               {}
func (*EncounterSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{16} }

type AvatarCustomizationSettings struct {
	Enabled          bool                                                       `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	AvatarType       PlayerAvatarType                                           `protobuf:"varint,2,opt,name=avatar_type,enum=POGOProtos.Data.Player.PlayerAvatarType" json:"avatar_type,omitempty"`
	Slot             []Slot                                                     `protobuf:"varint,3,rep,packed,name=slot,enum=POGOProtos.Enums.Slot" json:"slot,omitempty"`
	BundleName       string                                                     `protobuf:"bytes,4,opt,name=bundle_name" json:"bundle_name,omitempty"`
	AssetName        string                                                     `protobuf:"bytes,5,opt,name=asset_name" json:"asset_name,omitempty"`
	GroupName        string                                                     `protobuf:"bytes,6,opt,name=group_name" json:"group_name,omitempty"`
	SortOrder        int32                                                      `protobuf:"varint,7,opt,name=sort_order" json:"sort_order,omitempty"`
	UnlockType       AvatarCustomizationSettings_AvatarCustomizationUnlockType  `protobuf:"varint,8,opt,name=unlock_type,enum=POGOProtos.Settings.Master.AvatarCustomizationSettings_AvatarCustomizationUnlockType" json:"unlock_type,omitempty"`
	PromoType        []AvatarCustomizationSettings_AvatarCustomizationPromoType `protobuf:"varint,9,rep,packed,name=promo_type,enum=POGOProtos.Settings.Master.AvatarCustomizationSettings_AvatarCustomizationPromoType" json:"promo_type,omitempty"`
	UnlockBadgeType  BadgeType                                                  `protobuf:"varint,10,opt,name=unlock_badge_type,enum=POGOProtos.Enums.BadgeType" json:"unlock_badge_type,omitempty"`
	IapSku           string                                                     `protobuf:"bytes,11,opt,name=iap_sku" json:"iap_sku,omitempty"`
	UnlockBadgeLevel int32                                                      `protobuf:"varint,12,opt,name=unlock_badge_level" json:"unlock_badge_level,omitempty"`
	IconName         string                                                     `protobuf:"bytes,13,opt,name=icon_name" json:"icon_name,omitempty"`
}

func (m *AvatarCustomizationSettings) Reset()                    { *m = AvatarCustomizationSettings{} }
func (m *AvatarCustomizationSettings) String() string            { return proto.CompactTextString(m) }
func (*AvatarCustomizationSettings) ProtoMessage()               {}
func (*AvatarCustomizationSettings) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{17} }

func init() {
	proto.RegisterType((*IapItemDisplay)(nil), "POGOProtos.Settings.Master.IapItemDisplay")
	proto.RegisterType((*IapSettings)(nil), "POGOProtos.Settings.Master.IapSettings")
	proto.RegisterType((*MoveSettings)(nil), "POGOProtos.Settings.Master.MoveSettings")
	proto.RegisterType((*QuestSettings)(nil), "POGOProtos.Settings.Master.QuestSettings")
	proto.RegisterType((*BadgeSettings)(nil), "POGOProtos.Settings.Master.BadgeSettings")
	proto.RegisterType((*EquippedBadgeSettings)(nil), "POGOProtos.Settings.Master.EquippedBadgeSettings")
	proto.RegisterType((*TypeEffectiveSettings)(nil), "POGOProtos.Settings.Master.TypeEffectiveSettings")
	proto.RegisterType((*FormSettings)(nil), "POGOProtos.Settings.Master.FormSettings")
	proto.RegisterType((*FormSettings_Form)(nil), "POGOProtos.Settings.Master.FormSettings.Form")
	proto.RegisterType((*CameraSettings)(nil), "POGOProtos.Settings.Master.CameraSettings")
	proto.RegisterType((*GymLevelSettings)(nil), "POGOProtos.Settings.Master.GymLevelSettings")
	proto.RegisterType((*MoveSequenceSettings)(nil), "POGOProtos.Settings.Master.MoveSequenceSettings")
	proto.RegisterType((*PlayerLevelSettings)(nil), "POGOProtos.Settings.Master.PlayerLevelSettings")
	proto.RegisterType((*GymBattleSettings)(nil), "POGOProtos.Settings.Master.GymBattleSettings")
	proto.RegisterType((*PokemonUpgradeSettings)(nil), "POGOProtos.Settings.Master.PokemonUpgradeSettings")
	proto.RegisterType((*PokemonSettings)(nil), "POGOProtos.Settings.Master.PokemonSettings")
	proto.RegisterType((*ItemSettings)(nil), "POGOProtos.Settings.Master.ItemSettings")
	proto.RegisterType((*EncounterSettings)(nil), "POGOProtos.Settings.Master.EncounterSettings")
	proto.RegisterType((*AvatarCustomizationSettings)(nil), "POGOProtos.Settings.Master.AvatarCustomizationSettings")
	proto.RegisterEnum("POGOProtos.Settings.Master.PokemonSettings_BuddySize", PokemonSettings_BuddySize_name, PokemonSettings_BuddySize_value)
	proto.RegisterEnum("POGOProtos.Settings.Master.AvatarCustomizationSettings_AvatarCustomizationPromoType", AvatarCustomizationSettings_AvatarCustomizationPromoType_name, AvatarCustomizationSettings_AvatarCustomizationPromoType_value)
	proto.RegisterEnum("POGOProtos.Settings.Master.AvatarCustomizationSettings_AvatarCustomizationUnlockType", AvatarCustomizationSettings_AvatarCustomizationUnlockType_name, AvatarCustomizationSettings_AvatarCustomizationUnlockType_value)
}

func init() { proto.RegisterFile("settings_master.proto", fileDescriptor18) }

var fileDescriptor18 = []byte{
	// 2578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x59, 0xcd, 0x56, 0x1b, 0xc9,
	0x15, 0x1e, 0x09, 0x04, 0xd2, 0x15, 0x08, 0xd1, 0xfc, 0xb8, 0x0d, 0xd8, 0x83, 0x35, 0x9e, 0x1c,
	0x26, 0xc9, 0x78, 0x12, 0x79, 0xe2, 0x39, 0x27, 0x99, 0x59, 0x80, 0x91, 0x6d, 0x25, 0x60, 0x14,
	0x7e, 0x92, 0xe3, 0x6c, 0xea, 0x94, 0xba, 0x0b, 0x51, 0xa1, 0xbb, 0xab, 0x5d, 0x55, 0x2d, 0xd0,
	0xac, 0xb3, 0x4b, 0x5e, 0x21, 0xfb, 0xac, 0x92, 0x93, 0x45, 0x9e, 0x20, 0x79, 0x87, 0x3c, 0x43,
	0x36, 0x79, 0x86, 0x9c, 0xba, 0x55, 0x2d, 0x5a, 0x06, 0x03, 0x8b, 0x6c, 0x24, 0xb8, 0x7f, 0x75,
	0xeb, 0xd6, 0xfd, 0xf9, 0xaa, 0x04, 0x2b, 0x8a, 0x69, 0xcd, 0x93, 0x81, 0x22, 0x31, 0x55, 0x9a,
	0xc9, 0x67, 0xa9, 0x14, 0x5a, 0x78, 0x6b, 0xbd, 0x83, 0xd7, 0x07, 0x3d, 0xf3, 0xa7, 0x7a, 0x76,
	0xe4, 0x24, 0x9e, 0xed, 0xa3, 0xc4, 0x5a, 0x9d, 0x25, 0x59, 0xac, 0xac, 0xe0, 0xda, 0x32, 0x4f,
	0x86, 0x2c, 0xd1, 0x42, 0x8e, 0x08, 0xd7, 0x2c, 0x76, 0xd4, 0xf5, 0x0f, 0xac, 0x92, 0xf7, 0x19,
	0x53, 0xda, 0x31, 0x9b, 0x21, 0xd5, 0x94, 0xf4, 0x69, 0x38, 0x60, 0x8e, 0xf2, 0xe8, 0x43, 0xf1,
	0x54, 0x9c, 0xb3, 0x58, 0x24, 0x8e, 0xbd, 0xf6, 0x21, 0xbb, 0xb0, 0xd2, 0x22, 0x1a, 0x4b, 0x23,
	0x3a, 0xca, 0x7d, 0x6f, 0xfd, 0xad, 0x04, 0x8d, 0x2e, 0x4d, 0xbb, 0x9a, 0xc5, 0xbb, 0x5c, 0x19,
	0x96, 0x57, 0x87, 0x29, 0x75, 0x9e, 0xf9, 0xa5, 0xcd, 0xd2, 0x56, 0xcd, 0xfb, 0x06, 0xaa, 0x01,
	0xd5, 0x6c, 0x20, 0xe4, 0xc8, 0x2f, 0x6f, 0x96, 0xb6, 0x1a, 0xed, 0xcf, 0x9f, 0x15, 0xb6, 0xdb,
	0xc1, 0xdd, 0xbd, 0x11, 0x91, 0x70, 0x46, 0x5e, 0x3a, 0x61, 0xcf, 0x03, 0x50, 0x42, 0x6a, 0x22,
	0x64, 0xc8, 0xa4, 0x3f, 0xb5, 0x59, 0xda, 0xaa, 0x78, 0xcf, 0xa1, 0x6a, 0xbc, 0x21, 0x3c, 0x54,
	0xfe, 0xf4, 0xe6, 0xd4, 0x56, 0xa3, 0xfd, 0xa4, 0x68, 0xac, 0x9b, 0x47, 0xe7, 0x99, 0xb1, 0x84,
	0x1f, 0xdd, 0xd0, 0x6b, 0xc0, 0x4c, 0x20, 0xb2, 0x44, 0x2b, 0xbf, 0xb2, 0x39, 0xb5, 0x55, 0x69,
	0xfd, 0xa9, 0x0c, 0xf5, 0x2e, 0x4d, 0xf3, 0x40, 0x7b, 0x0f, 0x61, 0x31, 0xa4, 0x3c, 0x1a, 0x91,
	0xbe, 0x48, 0x32, 0x45, 0x02, 0xc1, 0x13, 0x85, 0xce, 0x57, 0xbc, 0x2d, 0xd8, 0xb4, 0xac, 0x90,
	0x9d, 0xb2, 0x24, 0x64, 0xd2, 0xc9, 0xa4, 0x57, 0x51, 0xf3, 0xcb, 0xc6, 0xa8, 0xf7, 0x43, 0x68,
	0xdd, 0x28, 0x19, 0xd3, 0xcb, 0x31, 0x49, 0xb9, 0x5d, 0x7c, 0x0e, 0x8f, 0x6e, 0x94, 0x0d, 0x32,
	0x29, 0x59, 0x12, 0x8c, 0x70, 0x6b, 0x35, 0xaf, 0x05, 0x6b, 0x31, 0x4f, 0x88, 0xe6, 0x31, 0x23,
	0x7d, 0xa6, 0x2f, 0x18, 0x4b, 0x48, 0x10, 0x51, 0x1e, 0x2b, 0x12, 0x9b, 0xbd, 0x94, 0xb6, 0xa6,
	0xbc, 0x75, 0x58, 0x2a, 0xfa, 0xce, 0x12, 0xda, 0x8f, 0x58, 0xe8, 0xcf, 0x6c, 0x96, 0xb6, 0xaa,
	0xde, 0x53, 0xd8, 0xb8, 0x71, 0x9d, 0x5c, 0x6a, 0xd6, 0x48, 0xb5, 0xfe, 0x3e, 0x05, 0x73, 0xfb,
	0x62, 0xc8, 0xc6, 0xf1, 0x68, 0x43, 0x3d, 0x16, 0x43, 0x16, 0xb3, 0x44, 0x13, 0x1e, 0x62, 0x24,
	0x1a, 0xed, 0x47, 0xd7, 0x0f, 0xad, 0x67, 0x03, 0x60, 0x74, 0xbd, 0x65, 0x98, 0xa3, 0x09, 0x8f,
	0xa9, 0xe6, 0x22, 0x31, 0x4a, 0x65, 0x77, 0x5c, 0x73, 0x2e, 0x4a, 0x44, 0x8f, 0x52, 0x86, 0xdb,
	0xbf, 0xcd, 0xd4, 0xf1, 0x28, 0x65, 0xde, 0x3c, 0x54, 0x52, 0x71, 0xc1, 0xa4, 0x3f, 0xbd, 0x59,
	0xda, 0x2a, 0x7b, 0x0f, 0x60, 0x81, 0x06, 0x41, 0x26, 0x69, 0x30, 0x22, 0xc1, 0x19, 0x4d, 0x02,
	0x86, 0x5b, 0x47, 0x46, 0x20, 0xb9, 0xe6, 0x01, 0x8d, 0x72, 0xc6, 0x0c, 0x32, 0x96, 0xa0, 0x7e,
	0xc6, 0x68, 0x44, 0x54, 0x40, 0x23, 0x2a, 0x71, 0x97, 0x65, 0x13, 0x28, 0xa5, 0x69, 0xcc, 0x13,
	0x4a, 0x22, 0xa1, 0x54, 0xce, 0xac, 0x22, 0xf3, 0x21, 0x2c, 0x6a, 0x49, 0x79, 0xc2, 0x24, 0x89,
	0xd8, 0x90, 0x45, 0x24, 0xe6, 0x89, 0x5f, 0xc3, 0x2d, 0x5c, 0x67, 0xd1, 0x4b, 0x1f, 0x90, 0xd5,
	0x84, 0xea, 0xf0, 0xf4, 0x92, 0x24, 0x34, 0x66, 0x7e, 0x1d, 0x73, 0x7d, 0x09, 0xea, 0x61, 0x26,
	0x6d, 0x10, 0x62, 0xe5, 0xcf, 0xa1, 0xd8, 0x63, 0x58, 0x0d, 0x69, 0x4c, 0x07, 0x8c, 0x5c, 0xf0,
	0x24, 0x14, 0x17, 0x44, 0x69, 0x2a, 0xb5, 0xe1, 0xcf, 0x23, 0x7f, 0x03, 0x96, 0x27, 0xf9, 0x2c,
	0x09, 0x0d, 0xb7, 0x81, 0xdc, 0x65, 0x98, 0x63, 0x09, 0x93, 0x03, 0x73, 0x88, 0x91, 0xa6, 0xfe,
	0x82, 0xa1, 0xb6, 0xfe, 0x58, 0x82, 0xf9, 0x5f, 0x9b, 0x22, 0x1f, 0x1f, 0xda, 0x57, 0x00, 0x58,
	0xf5, 0x36, 0xd0, 0xf6, 0xcc, 0xd6, 0xaf, 0x07, 0x1a, 0x95, 0x30, 0xcc, 0x5d, 0xa8, 0xdb, 0xe4,
	0x40, 0x35, 0x3c, 0xb0, 0x7a, 0xfb, 0xeb, 0x67, 0x1f, 0xef, 0x44, 0x56, 0xf7, 0xd9, 0xae, 0x51,
	0x9a, 0x58, 0xbb, 0xf5, 0x97, 0x12, 0xcc, 0xef, 0x98, 0x06, 0x53, 0xf4, 0x06, 0x3b, 0xce, 0x1d,
	0xde, 0xa0, 0x12, 0x7a, 0xe3, 0xe5, 0x0a, 0x92, 0x26, 0xe7, 0x2e, 0x7b, 0x16, 0x60, 0x56, 0x53,
	0x39, 0x60, 0xda, 0xd4, 0x8d, 0xa9, 0xb1, 0x6d, 0x68, 0x04, 0x34, 0xd5, 0x99, 0x64, 0x44, 0xb2,
	0x0b, 0x2a, 0x43, 0x2c, 0x94, 0x7a, 0xfb, 0x8b, 0xa2, 0xe5, 0x5d, 0xaa, 0xa9, 0x35, 0x6c, 0x3f,
	0x5f, 0x5a, 0x8d, 0x43, 0x54, 0x68, 0x8d, 0x60, 0xa5, 0xf3, 0x3e, 0xe3, 0x69, 0xca, 0xc2, 0x49,
	0x8f, 0x3f, 0x85, 0x07, 0xcc, 0x30, 0x6c, 0xa7, 0x24, 0x81, 0x10, 0x51, 0x28, 0x2e, 0xf0, 0x18,
	0x4b, 0x58, 0x69, 0x9f, 0xc2, 0x83, 0x80, 0xea, 0xe0, 0x8c, 0xa4, 0x52, 0xf4, 0x69, 0x9f, 0x47,
	0x5c, 0xbb, 0xaa, 0xc3, 0x0e, 0x50, 0x36, 0xe7, 0x7c, 0x1a, 0x31, 0x76, 0x03, 0xdf, 0x78, 0x5f,
	0x6e, 0xf5, 0x61, 0xc5, 0x6c, 0xb5, 0x73, 0x7a, 0xca, 0x02, 0xcd, 0x0b, 0xf5, 0xb6, 0x02, 0xf3,
	0x54, 0x6b, 0x1a, 0x9c, 0xe7, 0x49, 0x59, 0x42, 0x7b, 0x6d, 0xa8, 0x3b, 0x32, 0x06, 0xb1, 0x7c,
	0x8f, 0xda, 0x69, 0xfd, 0xab, 0x04, 0x73, 0xaf, 0x84, 0x8c, 0xc7, 0xb6, 0x7f, 0x0c, 0xb3, 0x79,
	0x9f, 0xfa, 0xe8, 0x29, 0x38, 0x03, 0xdd, 0xd0, 0xfb, 0x16, 0x2a, 0xa7, 0x42, 0xc6, 0x76, 0x47,
	0xf5, 0xf6, 0x97, 0xb7, 0x65, 0x43, 0x71, 0x19, 0xfc, 0x67, 0xed, 0x0d, 0x4c, 0x9b, 0x6f, 0xef,
	0x29, 0x4c, 0x1b, 0x2b, 0x6e, 0xc1, 0xd5, 0xeb, 0x0b, 0xa2, 0xd4, 0x1a, 0x78, 0x54, 0x29, 0xa6,
	0x49, 0x3f, 0x4b, 0xc2, 0x88, 0x91, 0x21, 0x8d, 0x32, 0xbb, 0xcb, 0x4a, 0xeb, 0xdf, 0x53, 0xd0,
	0x78, 0x49, 0x63, 0x26, 0xe9, 0x78, 0x23, 0x4b, 0x50, 0x4f, 0xd8, 0xa5, 0x26, 0x01, 0x92, 0xdd,
	0x6c, 0xf9, 0x16, 0xe6, 0x79, 0xa2, 0x99, 0x4c, 0x45, 0x84, 0x45, 0x87, 0x7e, 0xdf, 0x38, 0x60,
	0xac, 0xb5, 0x6e, 0x51, 0xd8, 0x7b, 0x0e, 0x75, 0x9b, 0x5f, 0x79, 0x73, 0x32, 0xba, 0x8f, 0x3f,
	0xa6, 0x7b, 0x8c, 0xa2, 0xe6, 0xb0, 0x18, 0x55, 0x8c, 0xf0, 0x84, 0xa8, 0x94, 0x31, 0x9b, 0x82,
	0x65, 0x6f, 0x15, 0x1a, 0x8c, 0x2a, 0x4d, 0x44, 0xa6, 0x1d, 0xbd, 0x82, 0x74, 0x1f, 0x9a, 0xe3,
	0x8e, 0xa0, 0x58, 0x20, 0x92, 0x50, 0xf9, 0x33, 0xc8, 0x59, 0x86, 0xb9, 0x0b, 0xca, 0xf5, 0x98,
	0x3a, 0x8b, 0xd4, 0x35, 0xf0, 0xb4, 0xa4, 0x89, 0xe2, 0x13, 0x1a, 0xd5, 0x5c, 0x83, 0x26, 0x83,
	0x88, 0x91, 0x90, 0x0d, 0x24, 0x63, 0x7e, 0x0d, 0xa9, 0xeb, 0xb0, 0x64, 0xa9, 0xe2, 0xf4, 0xd4,
	0x84, 0xd3, 0x31, 0x21, 0x57, 0x49, 0xb9, 0x49, 0x5a, 0x47, 0xad, 0xe7, 0x2a, 0x96, 0x3a, 0xa9,
	0x32, 0x87, 0xcc, 0x25, 0xa8, 0x4b, 0x11, 0x45, 0x39, 0x71, 0x1e, 0x89, 0x0f, 0x60, 0x21, 0xe4,
	0x4a, 0x9b, 0x26, 0x4b, 0x62, 0xa6, 0xcd, 0x28, 0x6b, 0xe4, 0xfb, 0x3e, 0x63, 0x7c, 0x70, 0xa6,
	0xcd, 0x48, 0x0c, 0x58, 0xa2, 0xfd, 0x85, 0x9c, 0x3e, 0x64, 0x52, 0x93, 0x40, 0x4b, 0x82, 0xdb,
	0xf7, 0x9b, 0x58, 0x04, 0x17, 0xd0, 0x7c, 0x3d, 0x8a, 0xf7, 0x4c, 0x27, 0x1d, 0x1f, 0xed, 0x3a,
	0x2c, 0x49, 0x53, 0x7b, 0x92, 0x85, 0x84, 0x5d, 0xa6, 0x4c, 0x72, 0x66, 0x9a, 0x79, 0x09, 0x6b,
	0x7e, 0x19, 0xe6, 0x22, 0x46, 0xcd, 0xec, 0x52, 0x91, 0xd0, 0xca, 0x4d, 0xdb, 0x15, 0x98, 0xcf,
	0xbb, 0xb2, 0x25, 0xdb, 0x06, 0xf1, 0x10, 0x16, 0x15, 0xa3, 0x32, 0x38, 0x23, 0xb8, 0x05, 0x5b,
	0x7d, 0xd3, 0x38, 0xf4, 0xb7, 0x60, 0xd9, 0x0e, 0xb9, 0xf7, 0x99, 0xb1, 0x3e, 0x5e, 0xbc, 0x09,
	0x55, 0xe5, 0x68, 0xb8, 0x62, 0xad, 0xf5, 0xe7, 0x12, 0x2c, 0xf5, 0x10, 0xe1, 0x4c, 0xba, 0xd9,
	0x84, 0xaa, 0x69, 0x4e, 0x24, 0xc9, 0x62, 0xe7, 0xdb, 0x47, 0x1c, 0x1f, 0xbb, 0x18, 0xa4, 0x24,
	0xce, 0x22, 0xcd, 0xd3, 0x88, 0x23, 0x82, 0x31, 0x81, 0xd9, 0x80, 0x65, 0x03, 0x09, 0xd8, 0x60,
	0xe0, 0x60, 0x94, 0x1d, 0x2b, 0x38, 0xec, 0x2a, 0x38, 0xf2, 0x0d, 0x37, 0x41, 0xc0, 0x62, 0x40,
	0x46, 0x51, 0xa6, 0x82, 0xc5, 0xf1, 0xdf, 0x29, 0x58, 0x7c, 0x3d, 0x8a, 0x77, 0xa8, 0xd6, 0xd1,
	0xd5, 0x3e, 0x4c, 0x02, 0xda, 0x39, 0x61, 0xb0, 0x89, 0x62, 0x01, 0x96, 0x08, 0x8e, 0xb6, 0x50,
	0x98, 0x8e, 0xe6, 0xb8, 0x81, 0x70, 0xcd, 0x1e, 0x73, 0x53, 0x32, 0x57, 0x01, 0x79, 0xa6, 0x4d,
	0x21, 0xe7, 0x11, 0xac, 0xb0, 0x84, 0xc5, 0x23, 0xe2, 0x1a, 0x10, 0x16, 0xd9, 0x90, 0x46, 0x6e,
	0x24, 0x3f, 0x86, 0xd5, 0xbc, 0x61, 0x31, 0x39, 0x34, 0x08, 0x31, 0xe7, 0x57, 0x72, 0xbe, 0x14,
	0x59, 0x12, 0x92, 0x1b, 0x52, 0xdf, 0xf0, 0x3f, 0x83, 0x75, 0x0b, 0x44, 0x10, 0xda, 0x18, 0x7f,
	0x69, 0x14, 0x8d, 0x0a, 0x95, 0x60, 0x84, 0x9e, 0xc2, 0x46, 0x4c, 0x2f, 0x79, 0x9c, 0xc5, 0xce,
	0x0b, 0x26, 0x2d, 0xee, 0xea, 0xe3, 0xc6, 0x71, 0x72, 0x57, 0xbc, 0x2f, 0xe0, 0x89, 0xa2, 0xb1,
	0x9d, 0x33, 0xb9, 0xb7, 0x0e, 0x78, 0x5d, 0x45, 0xbe, 0x86, 0x06, 0x57, 0xa1, 0x91, 0x1b, 0xb4,
	0xb1, 0x70, 0x63, 0xfc, 0x29, 0x6c, 0x14, 0x27, 0x2c, 0xae, 0x61, 0xf0, 0x83, 0x3e, 0x33, 0x48,
	0x41, 0xe3, 0x68, 0x2f, 0xc4, 0xf1, 0xfa, 0x80, 0x37, 0x47, 0xca, 0x13, 0x34, 0x3c, 0x71, 0x5c,
	0x76, 0xbc, 0xfb, 0xd0, 0x54, 0x17, 0x34, 0x9d, 0xd0, 0xb3, 0xa3, 0xfd, 0x07, 0xf0, 0xd8, 0x99,
	0xb4, 0xe3, 0x5f, 0xb2, 0x30, 0x0b, 0x50, 0xe4, 0xaa, 0x96, 0x4a, 0x5b, 0xe5, 0xd6, 0x1f, 0x4a,
	0xb0, 0xea, 0x7a, 0xf4, 0x49, 0x3a, 0x90, 0x34, 0xbc, 0x3a, 0xf5, 0x35, 0xf0, 0x32, 0x4b, 0xb2,
	0xb1, 0xb1, 0x0b, 0x5b, 0xec, 0xfa, 0x19, 0xac, 0xd3, 0x28, 0x12, 0x17, 0x2c, 0xb4, 0x64, 0x45,
	0x68, 0x5f, 0x0c, 0x99, 0xf3, 0xd1, 0xcd, 0x58, 0x0f, 0x20, 0xa0, 0x49, 0xe8, 0xf2, 0x62, 0x2a,
	0xcf, 0x5c, 0x03, 0x51, 0xc2, 0x4c, 0x69, 0x4b, 0xb6, 0x15, 0xf4, 0xcf, 0x1a, 0x2c, 0x38, 0x37,
	0x8a, 0x73, 0x3e, 0x07, 0x78, 0x63, 0xa4, 0x78, 0xeb, 0x84, 0x59, 0x32, 0xd8, 0x32, 0x64, 0x16,
	0x9c, 0x31, 0x97, 0x6e, 0x3f, 0x82, 0x69, 0xec, 0xc0, 0xd3, 0xf7, 0x81, 0x87, 0x5f, 0xc2, 0x0c,
	0x1e, 0x76, 0x1b, 0x93, 0xed, 0x4e, 0xf1, 0x5d, 0x98, 0x71, 0x23, 0x63, 0xe6, 0x6e, 0x84, 0xe3,
	0x14, 0x5d, 0xc7, 0xdf, 0xd6, 0x5a, 0xf2, 0x7e, 0xa6, 0x99, 0xf2, 0x7e, 0x09, 0xb5, 0x71, 0x4d,
	0x62, 0x7e, 0xd6, 0xdb, 0xdf, 0xdc, 0xc7, 0x50, 0x27, 0x57, 0x2a, 0xd8, 0xda, 0x81, 0x8a, 0xd2,
	0x54, 0x2b, 0xcc, 0xe0, 0x7a, 0xfb, 0xf9, 0x7d, 0xec, 0x1c, 0x19, 0x85, 0x82, 0x8d, 0x36, 0xd4,
	0xdf, 0x67, 0x3c, 0x38, 0x27, 0x06, 0xa8, 0x2b, 0x9c, 0x04, 0x77, 0x42, 0xf4, 0x17, 0xb0, 0x10,
	0xf0, 0x84, 0x19, 0x8c, 0x1e, 0x38, 0x3d, 0xb8, 0x8f, 0xde, 0x2a, 0x34, 0xae, 0xa0, 0xbd, 0xa9,
	0x58, 0x37, 0x45, 0xda, 0x30, 0xcf, 0x86, 0x22, 0xca, 0x1c, 0xe4, 0x57, 0x38, 0x3f, 0xee, 0x38,
	0x7e, 0xd3, 0xa5, 0xc6, 0x3a, 0x29, 0x4f, 0x73, 0x0c, 0xfc, 0x15, 0xcc, 0x48, 0x2a, 0xb9, 0x1e,
	0x61, 0x69, 0x34, 0xda, 0x9f, 0x7e, 0xd4, 0xc8, 0x21, 0x8a, 0x99, 0xaa, 0x32, 0x89, 0x17, 0xb2,
	0x4b, 0xe2, 0xe6, 0x4f, 0x6c, 0xab, 0xc5, 0x14, 0x6a, 0xce, 0xb9, 0xb0, 0x9c, 0xf3, 0x81, 0xdf,
	0x44, 0xd6, 0x0b, 0x58, 0x4c, 0xa9, 0x34, 0xd7, 0x9a, 0x42, 0xd2, 0x2e, 0xde, 0x9d, 0xb4, 0x57,
	0x43, 0x4e, 0xe9, 0x90, 0x84, 0x6c, 0xe8, 0x7b, 0x79, 0x47, 0xb9, 0x98, 0xa4, 0x2f, 0x21, 0x7d,
	0x03, 0x96, 0xcf, 0x63, 0x32, 0x1e, 0x98, 0x5a, 0x90, 0x33, 0x83, 0x1c, 0xfd, 0x65, 0xe4, 0x7e,
	0x0d, 0xb5, 0x53, 0x1a, 0x1b, 0xe4, 0xcd, 0x43, 0x7f, 0x05, 0x57, 0x7f, 0xf2, 0xd1, 0xd5, 0x5f,
	0xa1, 0x64, 0x37, 0xc4, 0xdb, 0x0e, 0x16, 0xaa, 0x16, 0xc4, 0x84, 0x70, 0xc8, 0xfc, 0xd5, 0xfc,
	0x82, 0x72, 0x1e, 0x93, 0x7e, 0x16, 0x86, 0xa3, 0xf1, 0x92, 0xfe, 0x03, 0x5c, 0xa9, 0x0b, 0x60,
	0xe9, 0x8a, 0x7f, 0xcf, 0x7c, 0x1f, 0x97, 0xfa, 0xd9, 0x3d, 0xd2, 0x6d, 0x4c, 0xde, 0x31, 0xda,
	0x47, 0xfc, 0x7b, 0xbc, 0xdf, 0xd9, 0xba, 0xb5, 0x81, 0xf0, 0x1f, 0xe2, 0x02, 0xfb, 0xd0, 0xbc,
	0x3a, 0xce, 0xbe, 0xa4, 0x49, 0x70, 0xe6, 0xaf, 0x21, 0x74, 0xbc, 0x57, 0x56, 0x77, 0x72, 0xdd,
	0x1d, 0x54, 0x6d, 0xf5, 0xa1, 0x76, 0xb5, 0x62, 0x13, 0xe6, 0x76, 0x4e, 0x76, 0x77, 0xdf, 0x91,
	0xfd, 0xce, 0x6e, 0xf7, 0x64, 0xbf, 0xf9, 0x89, 0xe7, 0x41, 0xc3, 0x52, 0x8e, 0xde, 0x1c, 0x9c,
	0xec, 0xed, 0x76, 0x0e, 0x9b, 0x25, 0x6f, 0x1e, 0x6a, 0x96, 0xb6, 0xd3, 0x7d, 0xdd, 0x2c, 0x5f,
	0x29, 0xbd, 0xda, 0x7b, 0xd7, 0x7d, 0xfb, 0xba, 0x39, 0xe5, 0x35, 0x00, 0x9c, 0xc0, 0xf6, 0xce,
	0xbb, 0xe6, 0x74, 0xeb, 0x1f, 0xb3, 0x30, 0xd7, 0xd5, 0x2c, 0x2e, 0xdc, 0x76, 0x67, 0xdd, 0x93,
	0x82, 0xeb, 0x5f, 0xf7, 0x78, 0x51, 0x78, 0x01, 0x35, 0xd4, 0x29, 0x00, 0xf3, 0xcf, 0xee, 0xd0,
	0xc2, 0x66, 0xf4, 0x93, 0xc2, 0x5b, 0x88, 0xbd, 0x0b, 0xdf, 0x00, 0x37, 0x27, 0x1e, 0x41, 0x16,
	0xa1, 0x16, 0x4a, 0x91, 0x92, 0x53, 0xc9, 0xde, 0xbb, 0xe9, 0xbb, 0x06, 0x1e, 0x92, 0x26, 0xae,
	0xa5, 0x16, 0x1b, 0x78, 0x1d, 0xa8, 0x9a, 0xd4, 0xee, 0xd3, 0x28, 0x72, 0xfd, 0xee, 0xd6, 0x83,
	0x40, 0xef, 0x7a, 0x4e, 0xa1, 0xd0, 0x5e, 0xb6, 0x61, 0x26, 0x15, 0x08, 0xa8, 0x6d, 0xaf, 0xfb,
	0xe9, 0x3d, 0x8c, 0x18, 0xf1, 0x49, 0x13, 0x92, 0x0d, 0xf9, 0x90, 0xb9, 0x36, 0x77, 0xb7, 0x89,
	0x43, 0x14, 0x9f, 0x34, 0xe1, 0x66, 0x7d, 0xed, 0x9e, 0x26, 0x2c, 0x26, 0x2a, 0x98, 0xf8, 0xce,
	0x5c, 0x45, 0x44, 0x88, 0x93, 0xbe, 0xde, 0xfe, 0xea, 0x4e, 0x03, 0xaf, 0x84, 0x08, 0x0b, 0xea,
	0xbf, 0x81, 0xc5, 0xab, 0x07, 0x37, 0x37, 0x68, 0x11, 0x0f, 0xd4, 0xdb, 0xbf, 0xb8, 0xd3, 0xd6,
	0x38, 0x09, 0xdc, 0xd0, 0x2e, 0xd8, 0xdd, 0x83, 0xea, 0x65, 0x4a, 0xfa, 0xc2, 0x0c, 0xd7, 0x39,
	0x34, 0xf7, 0xf3, 0x3b, 0xcd, 0x75, 0xc6, 0x00, 0x73, 0xc7, 0xe8, 0x15, 0xac, 0xbd, 0x84, 0x59,
	0x9e, 0x04, 0x2c, 0x51, 0x0c, 0xbb, 0x69, 0xbd, 0xdd, 0xbe, 0x87, 0x6f, 0x28, 0x5f, 0x30, 0xf2,
	0x16, 0xe6, 0x0d, 0x26, 0xe5, 0x49, 0x90, 0xf5, 0xa9, 0x16, 0x12, 0x1b, 0xf1, 0x1d, 0x53, 0xce,
	0xfa, 0x35, 0x18, 0x74, 0x73, 0xa5, 0x49, 0x7b, 0xa7, 0x42, 0x6a, 0x12, 0x8b, 0x90, 0x9f, 0x1a,
	0x10, 0xb6, 0x70, 0x4f, 0x7b, 0xaf, 0x84, 0xd4, 0xfb, 0x4e, 0xe9, 0xca, 0x5e, 0xeb, 0xaf, 0x25,
	0x58, 0x1c, 0x4f, 0xd3, 0x71, 0xf1, 0x6e, 0xc0, 0xb2, 0x4a, 0x79, 0xe2, 0x20, 0x9f, 0x3e, 0x93,
	0x4c, 0x9d, 0x89, 0x28, 0x74, 0xd8, 0xf7, 0x09, 0x3c, 0x64, 0x97, 0x01, 0x8b, 0x22, 0xd3, 0xf2,
	0xf5, 0x99, 0x14, 0x17, 0x05, 0x91, 0x72, 0x8e, 0x74, 0x07, 0x92, 0xd1, 0xeb, 0xec, 0xa9, 0xbc,
	0x93, 0x27, 0xdc, 0xb4, 0xf0, 0x0f, 0xb8, 0xd3, 0xf9, 0x9b, 0x52, 0xcc, 0x23, 0xa6, 0xb4, 0x48,
	0x58, 0x81, 0x69, 0x61, 0xfa, 0x7f, 0x2a, 0xb0, 0xbe, 0x3d, 0xa4, 0x9a, 0xca, 0x97, 0x99, 0xd2,
	0x22, 0xe6, 0xdf, 0xe3, 0x04, 0x1d, 0xbb, 0xbe, 0x00, 0xb3, 0xf9, 0x3b, 0x5c, 0x09, 0x5f, 0xeb,
	0xbe, 0x83, 0x3a, 0x45, 0xf9, 0x62, 0x5b, 0xd9, 0xba, 0xf6, 0xb4, 0x61, 0xaf, 0x26, 0xee, 0xcb,
	0x2e, 0x80, 0xbd, 0xe5, 0x29, 0x4c, 0x9b, 0xab, 0x90, 0xbb, 0xc6, 0xde, 0x70, 0xeb, 0x3e, 0x8a,
	0x84, 0x36, 0xf8, 0xcb, 0xdd, 0xb7, 0xf1, 0xd9, 0x6a, 0x1a, 0xaf, 0xd1, 0x1e, 0x80, 0xbd, 0x8a,
	0x23, 0xad, 0x92, 0xd3, 0x06, 0x52, 0x64, 0xa9, 0xa5, 0xcd, 0xe4, 0xb4, 0xc2, 0x8b, 0xec, 0x2c,
	0x76, 0x9c, 0xdf, 0x43, 0x3d, 0x4b, 0x22, 0x91, 0xbf, 0x52, 0x54, 0xd1, 0xeb, 0x93, 0xdb, 0x4e,
	0xf9, 0x96, 0xa0, 0xdc, 0xc4, 0x3b, 0x41, 0xeb, 0xb8, 0xc5, 0x33, 0x80, 0x54, 0x8a, 0x58, 0xd8,
	0xa5, 0x2c, 0xe8, 0x39, 0xfe, 0x3f, 0x2e, 0xd5, 0x33, 0xc6, 0x71, 0xa5, 0x17, 0xb0, 0xe8, 0x76,
	0x55, 0x78, 0xc6, 0x82, 0xbb, 0x9f, 0xb1, 0x16, 0x60, 0x96, 0xd3, 0x94, 0xa8, 0xf3, 0xcc, 0xbd,
	0x08, 0x1a, 0x80, 0x5e, 0x34, 0x64, 0x9b, 0xb5, 0xbd, 0x37, 0x2c, 0x42, 0x8d, 0x07, 0x22, 0xb1,
	0x11, 0x36, 0x95, 0x5b, 0x6b, 0xed, 0xc1, 0xc6, 0xad, 0x7e, 0x2d, 0x43, 0xf3, 0xe4, 0xed, 0x51,
	0xe7, 0x98, 0xf4, 0x0e, 0x0f, 0xf6, 0x0f, 0xc8, 0xf1, 0xbb, 0x5e, 0xa7, 0xf9, 0x89, 0x57, 0x85,
	0xe9, 0xa3, 0xed, 0xbd, 0x4e, 0xb3, 0xe4, 0xcd, 0x41, 0xf5, 0x55, 0x67, 0xfb, 0xf8, 0xe4, 0xb0,
	0xb3, 0xdb, 0x2c, 0xb7, 0x06, 0xf0, 0xe8, 0xf6, 0x80, 0xae, 0xc0, 0xa2, 0x35, 0x77, 0xf2, 0x76,
	0xef, 0xe0, 0xe5, 0xaf, 0x72, 0x7b, 0x75, 0x98, 0xdd, 0xed, 0xbc, 0xda, 0x3e, 0xd9, 0x3b, 0x6e,
	0x96, 0xcc, 0x48, 0xdd, 0xef, 0xec, 0x6e, 0xef, 0x91, 0xc3, 0xce, 0x6f, 0xb7, 0x0f, 0x77, 0xed,
	0x90, 0xed, 0x6e, 0xf7, 0xc8, 0xcb, 0xbd, 0x83, 0xe3, 0x37, 0x38, 0x64, 0x77, 0xaa, 0xbf, 0x9b,
	0xc1, 0x1f, 0x03, 0x54, 0xef, 0x93, 0x5e, 0xa9, 0x57, 0xee, 0x4d, 0xf5, 0xa6, 0x7b, 0x95, 0xde,
	0x4c, 0xdf, 0x52, 0x9f, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x42, 0xed, 0x91, 0x2e, 0xf7, 0x18,
	0x00, 0x00,
}
