// Code generated by protoc-gen-go.
// source: settings_master_item.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of QuestType from enums.proto

// Ignoring public import of EncounterType from enums.proto

// Ignoring public import of Filter from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of NotificationState from enums.proto

// Ignoring public import of Costume from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of Form from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of Slot from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of EggIncubator from inventory.proto

// Ignoring public import of InventoryUpgrade from inventory.proto

// Ignoring public import of InventoryUpgrades from inventory.proto

// Ignoring public import of EggIncubators from inventory.proto

// Ignoring public import of InventoryDelta from inventory.proto

// Ignoring public import of InventoryItemData from inventory.proto

// Ignoring public import of InventoryItem from inventory.proto

// Ignoring public import of DeletedItem from inventory.proto

// Ignoring public import of InventoryKey from inventory.proto

// Ignoring public import of AppliedItem from inventory.proto

// Ignoring public import of AppliedItems from inventory.proto

// Ignoring public import of Candy from inventory.proto

// Ignoring public import of EggIncubatorType from inventory.proto

// Ignoring public import of InventoryUpgradeType from inventory.proto

type BattleAttributes struct {
	StaPercent float32 `protobuf:"fixed32,1,opt,name=sta_percent" json:"sta_percent,omitempty"`
}

func (m *BattleAttributes) Reset()                    { *m = BattleAttributes{} }
func (m *BattleAttributes) String() string            { return proto.CompactTextString(m) }
func (*BattleAttributes) ProtoMessage()               {}
func (*BattleAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{0} }

type FortModifierAttributes struct {
	ModifierLifetimeSeconds   int32 `protobuf:"varint,1,opt,name=modifier_lifetime_seconds" json:"modifier_lifetime_seconds,omitempty"`
	TroyDiskNumPokemonSpawned int32 `protobuf:"varint,2,opt,name=troy_disk_num_pokemon_spawned" json:"troy_disk_num_pokemon_spawned,omitempty"`
}

func (m *FortModifierAttributes) Reset()                    { *m = FortModifierAttributes{} }
func (m *FortModifierAttributes) String() string            { return proto.CompactTextString(m) }
func (*FortModifierAttributes) ProtoMessage()               {}
func (*FortModifierAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{1} }

type FoodAttributes struct {
	ItemEffect        []ItemEffect `protobuf:"varint,1,rep,packed,name=item_effect,enum=POGOProtos.Enums.ItemEffect" json:"item_effect,omitempty"`
	ItemEffectPercent []float32    `protobuf:"fixed32,2,rep,packed,name=item_effect_percent" json:"item_effect_percent,omitempty"`
	GrowthPercent     float32      `protobuf:"fixed32,3,opt,name=growth_percent" json:"growth_percent,omitempty"`
}

func (m *FoodAttributes) Reset()                    { *m = FoodAttributes{} }
func (m *FoodAttributes) String() string            { return proto.CompactTextString(m) }
func (*FoodAttributes) ProtoMessage()               {}
func (*FoodAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{2} }

type EggIncubatorAttributes struct {
	IncubatorType      EggIncubatorType `protobuf:"varint,1,opt,name=incubator_type,enum=POGOProtos.Inventory.EggIncubatorType" json:"incubator_type,omitempty"`
	Uses               int32            `protobuf:"varint,2,opt,name=uses" json:"uses,omitempty"`
	DistanceMultiplier float32          `protobuf:"fixed32,3,opt,name=distance_multiplier" json:"distance_multiplier,omitempty"`
}

func (m *EggIncubatorAttributes) Reset()                    { *m = EggIncubatorAttributes{} }
func (m *EggIncubatorAttributes) String() string            { return proto.CompactTextString(m) }
func (*EggIncubatorAttributes) ProtoMessage()               {}
func (*EggIncubatorAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{3} }

type InventoryUpgradeAttributes struct {
	AdditionalStorage int32                `protobuf:"varint,1,opt,name=additional_storage" json:"additional_storage,omitempty"`
	UpgradeType       InventoryUpgradeType `protobuf:"varint,2,opt,name=upgrade_type,enum=POGOProtos.Inventory.InventoryUpgradeType" json:"upgrade_type,omitempty"`
}

func (m *InventoryUpgradeAttributes) Reset()                    { *m = InventoryUpgradeAttributes{} }
func (m *InventoryUpgradeAttributes) String() string            { return proto.CompactTextString(m) }
func (*InventoryUpgradeAttributes) ProtoMessage()               {}
func (*InventoryUpgradeAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{4} }

type PokeballAttributes struct {
	ItemEffect         ItemEffect `protobuf:"varint,1,opt,name=item_effect,enum=POGOProtos.Enums.ItemEffect" json:"item_effect,omitempty"`
	CaptureMulti       float32    `protobuf:"fixed32,2,opt,name=capture_multi" json:"capture_multi,omitempty"`
	CaptureMultiEffect float32    `protobuf:"fixed32,3,opt,name=capture_multi_effect" json:"capture_multi_effect,omitempty"`
	ItemEffectMod      float32    `protobuf:"fixed32,4,opt,name=item_effect_mod" json:"item_effect_mod,omitempty"`
}

func (m *PokeballAttributes) Reset()                    { *m = PokeballAttributes{} }
func (m *PokeballAttributes) String() string            { return proto.CompactTextString(m) }
func (*PokeballAttributes) ProtoMessage()               {}
func (*PokeballAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{5} }

type ReviveAttributes struct {
	StaPercent float32 `protobuf:"fixed32,1,opt,name=sta_percent" json:"sta_percent,omitempty"`
}

func (m *ReviveAttributes) Reset()                    { *m = ReviveAttributes{} }
func (m *ReviveAttributes) String() string            { return proto.CompactTextString(m) }
func (*ReviveAttributes) ProtoMessage()               {}
func (*ReviveAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{6} }

type PotionAttributes struct {
	StaPercent float32 `protobuf:"fixed32,1,opt,name=sta_percent" json:"sta_percent,omitempty"`
	StaAmount  int32   `protobuf:"varint,2,opt,name=sta_amount" json:"sta_amount,omitempty"`
}

func (m *PotionAttributes) Reset()                    { *m = PotionAttributes{} }
func (m *PotionAttributes) String() string            { return proto.CompactTextString(m) }
func (*PotionAttributes) ProtoMessage()               {}
func (*PotionAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{7} }

type IncenseAttributes struct {
	IncenseLifetimeSeconds                   int32         `protobuf:"varint,1,opt,name=incense_lifetime_seconds" json:"incense_lifetime_seconds,omitempty"`
	PokemonType                              []PokemonType `protobuf:"varint,2,rep,packed,name=pokemon_type,enum=POGOProtos.Enums.PokemonType" json:"pokemon_type,omitempty"`
	PokemonIncenseTypeProbability            float32       `protobuf:"fixed32,3,opt,name=pokemon_incense_type_probability" json:"pokemon_incense_type_probability,omitempty"`
	StandingTimeBetweenEncountersSeconds     int32         `protobuf:"varint,4,opt,name=standing_time_between_encounters_seconds" json:"standing_time_between_encounters_seconds,omitempty"`
	MovingTimeBetweenEncounterSeconds        int32         `protobuf:"varint,5,opt,name=moving_time_between_encounter_seconds" json:"moving_time_between_encounter_seconds,omitempty"`
	DistanceRequiredForShorterIntervalMeters int32         `protobuf:"varint,6,opt,name=distance_required_for_shorter_interval_meters" json:"distance_required_for_shorter_interval_meters,omitempty"`
	PokemonAttractedLengthSec                int32         `protobuf:"varint,7,opt,name=pokemon_attracted_length_sec" json:"pokemon_attracted_length_sec,omitempty"`
}

func (m *IncenseAttributes) Reset()                    { *m = IncenseAttributes{} }
func (m *IncenseAttributes) String() string            { return proto.CompactTextString(m) }
func (*IncenseAttributes) ProtoMessage()               {}
func (*IncenseAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{8} }

type ExperienceBoostAttributes struct {
	XpMultiplier    float32 `protobuf:"fixed32,1,opt,name=xp_multiplier" json:"xp_multiplier,omitempty"`
	BoostDurationMs int32   `protobuf:"varint,2,opt,name=boost_duration_ms" json:"boost_duration_ms,omitempty"`
}

func (m *ExperienceBoostAttributes) Reset()                    { *m = ExperienceBoostAttributes{} }
func (m *ExperienceBoostAttributes) String() string            { return proto.CompactTextString(m) }
func (*ExperienceBoostAttributes) ProtoMessage()               {}
func (*ExperienceBoostAttributes) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{9} }

func init() {
	proto.RegisterType((*BattleAttributes)(nil), "POGOProtos.Settings.Master.Item.BattleAttributes")
	proto.RegisterType((*FortModifierAttributes)(nil), "POGOProtos.Settings.Master.Item.FortModifierAttributes")
	proto.RegisterType((*FoodAttributes)(nil), "POGOProtos.Settings.Master.Item.FoodAttributes")
	proto.RegisterType((*EggIncubatorAttributes)(nil), "POGOProtos.Settings.Master.Item.EggIncubatorAttributes")
	proto.RegisterType((*InventoryUpgradeAttributes)(nil), "POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes")
	proto.RegisterType((*PokeballAttributes)(nil), "POGOProtos.Settings.Master.Item.PokeballAttributes")
	proto.RegisterType((*ReviveAttributes)(nil), "POGOProtos.Settings.Master.Item.ReviveAttributes")
	proto.RegisterType((*PotionAttributes)(nil), "POGOProtos.Settings.Master.Item.PotionAttributes")
	proto.RegisterType((*IncenseAttributes)(nil), "POGOProtos.Settings.Master.Item.IncenseAttributes")
	proto.RegisterType((*ExperienceBoostAttributes)(nil), "POGOProtos.Settings.Master.Item.ExperienceBoostAttributes")
}

func init() { proto.RegisterFile("settings_master_item.proto", fileDescriptor27) }

var fileDescriptor27 = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0xfd, 0x12, 0x7e, 0xbe, 0x6a, 0x80, 0x00, 0xa6, 0xd0, 0x90, 0x82, 0x9a, 0x46, 0xa5, 0x44,
	0x95, 0x88, 0x5a, 0x50, 0xaf, 0x2a, 0x55, 0x2d, 0x52, 0xa8, 0x72, 0x81, 0x88, 0xfa, 0x73, 0xd3,
	0x9b, 0xd5, 0xda, 0x9e, 0x98, 0x15, 0xde, 0x5d, 0x77, 0x77, 0x1c, 0x48, 0x6f, 0xfb, 0x0c, 0x7d,
	0xb1, 0x3e, 0x51, 0xb5, 0x6b, 0xc7, 0x72, 0x7f, 0x28, 0x77, 0xd6, 0xe8, 0xcc, 0xcc, 0x39, 0x67,
	0x8e, 0x17, 0x3a, 0x16, 0x89, 0x84, 0x4a, 0x2c, 0x93, 0xdc, 0x12, 0x1a, 0x26, 0x08, 0xe5, 0x20,
	0x33, 0x9a, 0x74, 0xf0, 0x68, 0x7c, 0xf1, 0xee, 0x62, 0xec, 0x3e, 0xed, 0xe0, 0x43, 0x09, 0x1b,
	0x9c, 0x7b, 0xd8, 0x60, 0x44, 0x28, 0x3b, 0x2b, 0xa8, 0x72, 0x69, 0x0b, 0x74, 0x67, 0x5d, 0xa8,
	0x29, 0x2a, 0xd2, 0x66, 0x56, 0x14, 0x7a, 0x87, 0xb0, 0x71, 0xca, 0x89, 0x52, 0x7c, 0x4b, 0x64,
	0x44, 0x98, 0x13, 0xda, 0x60, 0x0b, 0x56, 0x2c, 0x71, 0x96, 0xa1, 0x89, 0x50, 0x51, 0xbb, 0xd1,
	0x6d, 0xf4, 0x9b, 0xbd, 0x10, 0x76, 0xce, 0xb4, 0xa1, 0x73, 0x1d, 0x8b, 0x89, 0x40, 0x53, 0x83,
	0x3f, 0x86, 0x5d, 0x59, 0x56, 0x59, 0x2a, 0x26, 0x48, 0x42, 0x22, 0xb3, 0x18, 0x69, 0x15, 0x5b,
	0xdf, 0xbc, 0x14, 0x1c, 0xc0, 0x3e, 0x19, 0x3d, 0x63, 0xb1, 0xb0, 0x57, 0x4c, 0xe5, 0x92, 0x65,
	0xfa, 0x0a, 0xa5, 0x56, 0xcc, 0x66, 0xfc, 0x5a, 0x61, 0xdc, 0x6e, 0x3a, 0x58, 0xef, 0x06, 0x5a,
	0x67, 0x5a, 0xc7, 0xb5, 0xd9, 0x2f, 0x60, 0xc5, 0x69, 0x65, 0x38, 0x99, 0x60, 0xe4, 0xa8, 0x2c,
	0xf4, 0x5b, 0xc7, 0x7b, 0x83, 0x9a, 0xe6, 0xa1, 0x57, 0xe7, 0x94, 0x0e, 0x3d, 0x26, 0x78, 0x08,
	0x5b, 0xb5, 0x96, 0x4a, 0x45, 0xb3, 0xbb, 0xd0, 0x6f, 0x06, 0x3b, 0xd0, 0x4a, 0x8c, 0xbe, 0xa6,
	0xcb, 0xaa, 0xbe, 0xe0, 0xd5, 0x7d, 0x6b, 0xc0, 0xce, 0x30, 0x49, 0x46, 0x2a, 0xca, 0x43, 0x4e,
	0xba, 0x2e, 0xef, 0x35, 0xb4, 0xc4, 0xbc, 0xcc, 0x68, 0x96, 0xa1, 0xd7, 0xd4, 0x3a, 0x7e, 0x5a,
	0x67, 0x31, 0xaa, 0x6c, 0xad, 0x4f, 0xf9, 0x38, 0xcb, 0x30, 0x58, 0x85, 0xc5, 0xdc, 0xa2, 0x2d,
	0x24, 0x3a, 0x76, 0xb1, 0xb0, 0xc4, 0x55, 0x84, 0x4c, 0xe6, 0x29, 0x89, 0x2c, 0x15, 0x68, 0x4a,
	0x16, 0x5f, 0xa1, 0x53, 0x0d, 0xfa, 0x94, 0x25, 0x86, 0xc7, 0xf5, 0xb3, 0x74, 0x20, 0xe0, 0x71,
	0x2c, 0x48, 0x68, 0xc5, 0x53, 0x66, 0x49, 0x1b, 0x9e, 0x60, 0x69, 0xf0, 0x1b, 0x58, 0xcd, 0x8b,
	0x86, 0x82, 0x62, 0xd3, 0x53, 0x7c, 0xf6, 0x77, 0x8a, 0xbf, 0xef, 0x70, 0x34, 0x7b, 0xdf, 0x1b,
	0x10, 0x8c, 0xf5, 0x15, 0x86, 0x3c, 0x4d, 0xff, 0x75, 0x80, 0xc6, 0x9d, 0x07, 0xd8, 0x86, 0xb5,
	0x88, 0x67, 0x94, 0x9b, 0x52, 0xa1, 0x27, 0xd3, 0x0c, 0xf6, 0xe0, 0xfe, 0x2f, 0xe5, 0xf9, 0x48,
	0x2f, 0x3d, 0x78, 0x00, 0xeb, 0xf5, 0xab, 0x49, 0x1d, 0xb7, 0x17, 0xbd, 0x27, 0x87, 0xb0, 0xf1,
	0x1e, 0xa7, 0x62, 0x7a, 0x67, 0x40, 0x5f, 0xc1, 0xc6, 0x58, 0x3b, 0x73, 0xee, 0x00, 0x06, 0x01,
	0x80, 0x2b, 0x72, 0xa9, 0x73, 0x9f, 0x0b, 0x97, 0xbc, 0x1f, 0x4d, 0xd8, 0x1c, 0xa9, 0x08, 0x95,
	0xad, 0xef, 0xe9, 0x42, 0x5b, 0x14, 0xc5, 0xdb, 0x82, 0x7d, 0x02, 0xab, 0xf3, 0x28, 0x97, 0xbe,
	0xbb, 0x80, 0xee, 0xff, 0xe9, 0xcf, 0xb8, 0x40, 0xf9, 0x44, 0xf4, 0xa1, 0x3b, 0x6f, 0x9a, 0x8f,
	0x77, 0xcd, 0x2c, 0x33, 0x3a, 0xe4, 0xa1, 0x48, 0x05, 0xcd, 0x4a, 0x57, 0x9e, 0x43, 0xdf, 0x65,
	0x25, 0x16, 0x2a, 0x61, 0x7e, 0x7b, 0x88, 0x74, 0x8d, 0xa8, 0x18, 0xaa, 0xc8, 0xb1, 0x47, 0x63,
	0x2b, 0x42, 0x8b, 0x9e, 0xd0, 0x11, 0x1c, 0x48, 0x3d, 0xbd, 0x1d, 0x5f, 0xc1, 0x97, 0x3c, 0xfc,
	0x25, 0x1c, 0x55, 0x71, 0x34, 0xf8, 0x25, 0x17, 0x06, 0x63, 0x36, 0xd1, 0x86, 0xd9, 0x4b, 0x6d,
	0xfc, 0x4b, 0xe3, 0x9a, 0xa6, 0x3c, 0x65, 0x12, 0xdd, 0xb6, 0xf6, 0xb2, 0x6f, 0x7b, 0x02, 0x7b,
	0x73, 0x05, 0x9c, 0xc8, 0xf0, 0x88, 0x30, 0x66, 0x29, 0xaa, 0x84, 0x2e, 0xdd, 0x82, 0xf6, 0xff,
	0xde, 0xd4, 0x73, 0xd8, 0x1d, 0xde, 0x64, 0x68, 0x04, 0xaa, 0x08, 0x4f, 0xb5, 0xb6, 0x54, 0xf3,
	0x76, 0x1b, 0xd6, 0x6e, 0xb2, 0xfa, 0x2f, 0x50, 0x1c, 0x67, 0x17, 0x36, 0x43, 0x87, 0x64, 0x71,
	0x6e, 0xb8, 0xbb, 0x26, 0x93, 0xe5, 0xaf, 0x73, 0x7a, 0xef, 0xf3, 0xb2, 0x7f, 0xb3, 0xec, 0xf8,
	0xbf, 0x71, 0x23, 0x2c, 0xbe, 0x4f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x81, 0x59, 0x72, 0x4f,
	0x1c, 0x05, 0x00, 0x00,
}
